### ISSUE TITLE
Can't display storefront after #2758 applied

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2762]
Receiving the following log when attempting to display the storefront after applying most recent changes:
```
[23-Aug-2019 12:09:37 America/New_York] Request URI: /zc157/, IP address: ::1
#1  require(C:\xampp\htdocs\zc157\includes\autoload_func.php) called at [C:\xampp\htdocs\zc157\includes\application_top.php:171]
#2  require(C:\xampp\htdocs\zc157\includes\application_top.php) called at [C:\xampp\htdocs\zc157\index.php:26]
--> PHP Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\zc157\includes\autoload_func.php on line 19.

[23-Aug-2019 12:09:37 America/New_York] PHP Fatal error:  Uncaught Error: Call to a member function Execute() on null in C:\xampp\htdocs\zc157\includes\counter.php:23
Stack trace:
#0 C:\xampp\htdocs\zc157\includes\application_top.php(177): require()
#1 C:\xampp\htdocs\zc157\index.php(26): require('C:\\xampp\\htdocs...')
#2 {main}
  thrown in C:\xampp\htdocs\zc157\includes\counter.php on line 23

[23-Aug-2019 12:09:37 America/New_York] Request URI: /zc157/, IP address: ::1
--> PHP Fatal error: Uncaught Error: Call to a member function Execute() on null in C:\xampp\htdocs\zc157\includes\counter.php:23
Stack trace:
#0 C:\xampp\htdocs\zc157\includes\application_top.php(177): require()
#1 C:\xampp\htdocs\zc157\index.php(26): require('C:\\xampp\\htdocs...')
#2 {main}
  thrown in C:\xampp\htdocs\zc157\includes\counter.php on line 23.

```

**Comment by zcwilt** [comment]
oops. Haven't yet applied the new initSystem infrastructue to store side so autoload_func.php will break

Will provide a temp fix for store side asap.

Thanks.
