### ISSUE TITLE
Fatal error:  Uncaught RuntimeException: A facade root has not been set

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3753]
Lately I am getting an error 500 on a fresh ZC158 installation. Not sure when it started. And happens in front and backend
Zen Cart Log
```
[18-Jul-2020 08:11:22 UTC] PHP Fatal error:  Uncaught RuntimeException: A facade root has not been set. in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:236
Stack trace:
#0 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(407): Illuminate\Support\Facades\Facade::__callStatic()
#1 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(384): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths()
#2 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\Foundation\Exceptions\Handler->renderHttpException()
#3 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(192): Illuminate\Foundation\Exceptions\Handler->prepareResponse()
#4 /######/public_html/app/Exceptions/Handler.php(52): Illuminate\Foundation\Exceptions\Handler->render()
#5 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(326): App\Exceptions\Handler->render()
#6 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(120): Illuminate\Foundation\Http\Kernel->renderException()
#7 /######/public_html/includes/illuminate_bootstrap.php(10): Illuminate\Foundation\Http\Kernel->handle()
#8 /######/public_html/admin/includes/application_bootstrap.php(160): require('/home/zen4all-d...')
#9 /######/public_html/admin/index.php(5): require_once('/home/zen4all-d...')
#10 {main}
  thrown in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 236

[18-Jul-2020 08:11:22 UTC] Request URI: /admin/, IP address: ######
--> PHP Fatal error: Uncaught RuntimeException: A facade root has not been set. in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:236
Stack trace:
#0 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(407): Illuminate\Support\Facades\Facade::__callStatic()
#1 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(384): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths()
#2 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\Foundation\Exceptions\Handler->renderHttpException()
#3 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(192): Illuminate\Foundation\Exceptions\Handler->prepareResponse()
#4 /######/public_html/app/Exceptions/Handler.php(52): Illuminate\Foundation\Exceptions\Handler->render()
#5 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(326): App\Exceptions\Handler->render()
#6 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(120): Illuminate\Foundation\Http\Kernel->renderException()
#7 /######/public_html/includes/illuminate_bootstrap.php(10): Illuminate\Foundation\Http\Kernel->handle()
#8 /######/public_html/admin/includes/application_bootstrap.php(160): require('/home/zen4all-d...')
#9 /######/public_html/admin/index.php(5): require_once('/home/zen4all-d...')
#10 {main}
  thrown in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 236.

```
Laravel log
```
[2020-07-18 08:11:22] local.ERROR: Class App\Exceptions\HandleExceptions does not exist {"exception":"[object] (ReflectionException(code: -1): Class App\\Exceptions\\HandleExceptions does not exist at /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:788)
[stacktrace]
#0 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(788): ReflectionClass->__construct()
#1 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\Container->build()
#2 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\\Container\\Container->resolve()
#3 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\\Container\\Container->make()
#4 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(210): Illuminate\\Foundation\\Application->make()
#5 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#7 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#8 /######/public_html/includes/illuminate_bootstrap.php(10): Illuminate\\Foundation\\Http\\Kernel->handle()
#9 /######/public_html/admin/includes/application_bootstrap.php(160): require('/home/zen4all-d...')
#10 /######/public_html/admin/index.php(5): require_once('/home/zen4all-d...')
#11 {main}
"}

**Comment by zcwilt** [comment]
Sorry, my fault missed a file on a previous commit 
#3754 should fix this.

**Comment by Zen4All** [comment]
Sorry that didn't work.
New log
laravel:
```
[2020-07-18 10:10:50] local.ERROR: include(/######/public_html/app/vendor/composer/../../Providers/AppServiceProvider.php): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(/######/public_html/app/vendor/composer/../../Providers/AppServiceProvider.php): failed to open stream: No such file or directory at /######/public_html/app/vendor/composer/ClassLoader.php:444)
[stacktrace]
#0 /######/public_html/app/vendor/composer/ClassLoader.php(444): App\\Exceptions\\HandleExceptions->handleError()
#1 /######/public_html/app/vendor/composer/ClassLoader.php(444): include()
#2 /######/public_html/app/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile()
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#4 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(208): spl_autoload_call()
#5 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\\Foundation\\ProviderRepository->createProvider()
#6 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest()
#7 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(584): Illuminate\\Foundation\\ProviderRepository->load()
#8 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#9 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(210): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#10 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith()
#11 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#12 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#13 /######/public_html/includes/illuminate_bootstrap.php(10): Illuminate\\Foundation\\Http\\Kernel->handle()
#14 /######/public_html/######/includes/application_bootstrap.php(160): require('/home/zen4all-d...')
#15 /######/public_html/######/index.php(5): require_once('/home/zen4all-d...')
#16 {main}
"} 
[2020-07-18 10:10:50] local.ERROR: Class view does not exist {"exception":"[object] (ReflectionException(code: -1): Class view does not exist at /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:788)
[stacktrace]
#0 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(788): ReflectionClass->__construct()
#1 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\Container->build()
#2 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\\Container\\Container->resolve()
#3 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\\Container\\Container->make()
#4 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1227): Illuminate\\Foundation\\Application->make()
#5 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(176): Illuminate\\Container\\Container->offsetGet()
#6 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(144): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()
#7 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(233): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#8 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(407): Illuminate\\Support\\Facades\\Facade::__callStatic()
#9 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(384): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()
#10 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#11 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(192): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#12 /######/public_html/app/Exceptions/Handler.php(52): Illuminate\\Foundation\\Exceptions\\Handler->render()
#13 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(326): App\\Exceptions\\Handler->render()
#14 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(120): Illuminate\\Foundation\\Http\\Kernel->renderException()
#15 /######/public_html/includes/illuminate_bootstrap.php(10): Illuminate\\Foundation\\Http\\Kernel->handle()
#16 /######/public_html/######/includes/application_bootstrap.php(160): require('/home/zen4all-d...')
#17 /######/public_html/######/index.php(5): require_once('/home/zen4all-d...')
#18 {main}
"} 
[2020-07-18 10:10:50] local.ERROR: Uncaught ReflectionException: Class view does not exist in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:788
Stack trace:
#0 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(788): ReflectionClass->__construct()
#1 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build()
#2 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve()
#3 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make()
#4 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1227): Illuminate\Foundation\Application->make()
#5 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(176): Illuminate\Container\Container->offsetGet()
#6 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(144): Illuminate\Support\Facades\Facade::resolveFacadeInstance()
#7 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(233): Illuminate\Support\Facades\Facade::getFacadeRoot()
#8 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(407): Illuminate\Support\Facades\Facade::__callStatic()
#9 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(384): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths()
#10 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\Foundation\Exceptions\Handler->renderHttpException()
#11 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(192): Illuminate\Foundation\Exceptions\Handler->prepareResponse()
#12 /######/public_html/app/Exceptions/Handler.php(52): Illuminate\Foundation\Exceptions\Handler->render()
#13 /######/public_html/app/Exceptions/HandleExceptions.php(123): App\Exceptions\Handler->render()
#14 /######/public_html/app/Exceptions/HandleExceptions.php(100): App\Exceptions\HandleExceptions->renderHttpResponse()
#15 [internal function]: App\Exceptions\HandleExceptions->handleException()
#16 {main}
  thrown {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught ReflectionException: Class view does not exist in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:788
Stack trace:
#0 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(788): ReflectionClass->__construct()
#1 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\Container->build()
#2 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\\Container\\Container->resolve()
#3 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\\Container\\Container->make()
#4 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1227): Illuminate\\Foundation\\Application->make()
#5 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(176): Illuminate\\Container\\Container->offsetGet()
#6 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(144): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()
#7 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(233): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#8 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(407): Illuminate\\Support\\Facades\\Facade::__callStatic()
#9 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(384): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()
#10 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#11 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(192): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#12 /######/public_html/app/Exceptions/Handler.php(52): Illuminate\\Foundation\\Exceptions\\Handler->render()
#13 /######/public_html/app/Exceptions/HandleExceptions.php(123): App\\Exceptions\\Handler->render()
#14 /######/public_html/app/Exceptions/HandleExceptions.php(100): App\\Exceptions\\HandleExceptions->renderHttpResponse()
#15 [internal function]: App\\Exceptions\\HandleExceptions->handleException()
#16 {main}
  thrown at /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:788)
[stacktrace]
#0 {main}
"} 
```
Zen Cart log
```
[18-Jul-2020 10:10:50 UTC] PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:788
Stack trace:
#0 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(788): ReflectionClass->__construct()
#1 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build()
#2 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve()
#3 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make()
#4 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1227): Illuminate\Foundation\Application->make()
#5 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(176): Illuminate\Container\Container->offsetGet()
#6 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(144): Illuminate\Support\Facades\Facade::resolveFacadeInstance()
#7 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(233): Illuminate\Support\Facades\Facade::getFacadeRoot()
#8 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(407): Illuminate\Support\Facades\Facade::__callStatic()
#9 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(384): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths()
#10 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\Foundation\Exceptions\Handler->renderHttpException()
#11 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(192): Illuminate\Foundation\Exceptions\Handler->prepareResponse()
#12 /######/public_html/app/Exceptions/Handler.php(52): Illuminate\Foundation\Exceptions\Handler->render()
#13 /######/public_html/app/Exceptions/HandleExceptions.php(123): App\Exceptions\Handler->render()
#14 /######/public_html/app/Exceptions/HandleExceptions.php(100): App\Exceptions\HandleExceptions->renderHttpResponse()
#15 [internal function]: App\Exceptions\HandleExceptions->handleException()
#16 {main}
  thrown in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 788

[18-Jul-2020 10:10:50 UTC] Request URI: /######/, IP address: ######
--> PHP Fatal error: Uncaught ReflectionException: Class view does not exist in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:788
Stack trace:
#0 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(788): ReflectionClass->__construct()
#1 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build()
#2 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve()
#3 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make()
#4 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1227): Illuminate\Foundation\Application->make()
#5 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(176): Illuminate\Container\Container->offsetGet()
#6 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(144): Illuminate\Support\Facades\Facade::resolveFacadeInstance()
#7 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(233): Illuminate\Support\Facades\Facade::getFacadeRoot()
#8 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(407): Illuminate\Support\Facades\Facade::__callStatic()
#9 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(384): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths()
#10 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\Foundation\Exceptions\Handler->renderHttpException()
#11 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(192): Illuminate\Foundation\Exceptions\Handler->prepareResponse()
#12 /######/public_html/app/Exceptions/Handler.php(52): Illuminate\Foundation\Exceptions\Handler->render()
#13 /######/public_html/app/Exceptions/HandleExceptions.php(123): App\Exceptions\Handler->render()
#14 /######/public_html/app/Exceptions/HandleExceptions.php(100): App\Exceptions\HandleExceptions->renderHttpResponse()
#15 [internal function]: App\Exceptions\HandleExceptions->handleException()
#16 {main}
  thrown in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 788.
[18-Jul-2020 10:10:50 UTC] PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:788
Stack trace:
#0 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(788): ReflectionClass->__construct()
#1 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build()
#2 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve()
#3 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make()
#4 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(1227): Illuminate\Foundation\Application->make()
#5 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(176): Illuminate\Container\Container->offsetGet()
#6 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(144): Illuminate\Support\Facades\Facade::resolveFacadeInstance()
#7 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(233): Illuminate\Support\Facades\Facade::getFacadeRoot()
#8 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(407): Illuminate\Support\Facades\Facade::__callStatic()
#9 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(384): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths()
#10 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\Foundation\Exceptions\Handler->renderHttpException()
#11 /######/public_html/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(192): Illuminate\Foundation\Exceptions\Handler->prepareResponse()
#12 /######/public_html/app/Exceptions/Handler.php(52): Illuminate\Foundation\Exceptions\Handler->render()
#13 /######/public_html/app/Exceptions/HandleExceptions.php(123): App\Exceptions\Handler->render()
#14 /######/public_html/app/Exceptions/HandleExceptions.php(100): App\Exceptions\HandleExceptions->renderHttpResponse()
#15 /######/public_html/app/Exceptions/HandleExceptions.php(135): App\Exceptions\HandleExceptions->handleException()
#16 [internal function]: App\Exceptions\HandleExceptions->handleShutdown()
#17 {main}
  thrown in /######/public_html/app/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 788
```

**Comment by scottcwilson** [comment]
I just updated and things are working for me, both front and back end.

**Comment by zcwilt** [comment]
@Zen4All 
Do you have any extra logging enabled.

**Comment by Zen4All** [comment]
> @Zen4All
> Do you have any extra logging enabled.

No, it is a default install.

**Comment by drbyte** [comment]
@Zen4All those `failed to open stream: No such file or directory` and `Class view does not exist` errors seem to suggest that the Composer files aren't firing (they load up all the namespaced files/classes, and register autoloaders), or the content that's cached by the composer autoload files is outdated ..... or that a bunch of files just aren't present.

There are a bunch of `.gitignore` rules that normally cause exclusions of directories named "vendor". But we've specifically overridden those rules temporarily to put these files into core. Is something in your local environment perhaps also ignoring updates for these directories when doing checkouts?

**Comment by Zen4All** [comment]
I did a fresh install today, using a downloaded zip from GitHub with the latest file set, and all is working again.
