### ISSUE TITLE
zc158: Fatal error, missing installedPlugins class

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3817]
Seeing this log (both storefront and admin) using the just-downloaded v158 branch:
```

[02-Aug-2020 11:23:55 UTC] Request URI: /zc158/, IP address: ::1
--> PHP Fatal error: Uncaught ReflectionException: Class installedPlugins does not exist in C:\xampp\htdocs\zc158\app\vendor\laravel\framework\src\Illuminate\Container\Container.php:788
Stack trace:
#0 C:\xampp\htdocs\zc158\app\vendor\laravel\framework\src\Illuminate\Container\Container.php(788): ReflectionClass->__construct('installedPlugin...')
#1 C:\xampp\htdocs\zc158\app\vendor\laravel\framework\src\Illuminate\Container\Container.php(667): Illuminate\Container\Container->build('installedPlugin...')
#2 C:\xampp\htdocs\zc158\app\vendor\laravel\framework\src\Illuminate\Container\Container.php(615): Illuminate\Container\Container->resolve('installedPlugin...', Array)
#3 C:\xampp\htdocs\zc158\app\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(767): Illuminate\Container\Container->make('installedPlugin...', Array)
#4 C:\xampp\htdocs\zc158\includes\application_top.php(190): Illuminate\Foundation\Application->make('installedPlugin...')
#5 C:\xampp\htdocs\zc158\index.php(25): require('C:\\xampp\\htdocs...')
#6 {main}
  thrown in C:\xampp\htdocs\zc158\app\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 788.
```

**Comment by scottcwilson** [comment]
Hmmm... mine is still working.  Just checked and both of us are even with zencart:v158.

**Comment by lat9** [comment]
Do I need to re-install?  I simply updated the processing files.

**Comment by scottcwilson** [comment]
Try re-installing and see if that fixes it.  If it doesn't, I'll re-install so we can confirm the finding.

**Comment by lat9** [comment]
I re-installed and the issue 'went away'.  My question is **_Why_**?  Is there now some kind of hidden configuration setting?

**Comment by dbltoe** [comment]
In the Air Force (Crypto Electronics), we called it FM.
😁

**Comment by lat9** [comment]
Actually, in this case, it's PFM.

**Comment by lat9** [comment]
Just rechecked.  No error when running PHP 7.3, but with PHP 7.4 those errors are still present on a fresh install.

**Comment by scottcwilson** [comment]
Mine looks ok on PHP 7.4 but I haven't re-created the DB in a while.  Anyone else?

**Comment by Zen4All** [comment]
Could this also be related to #3753?

**Comment by lat9** [comment]
I dunno, here's the Laravel log:
```
[2020-08-02 11:23:55] local.ERROR: could not find driver (SQL: update `plugin_control` set `infs` = 0) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (SQL: update `plugin_control` set `infs` = 0) at C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:664, PDOException(code: 0): could not find driver at C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php:70)
[stacktrace]
#0 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('update `plugin_...', Array, Object(Closure))
#1 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(490): Illuminate\\Database\\Connection->run('update `plugin_...', Array, Object(Closure))
#2 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(423): Illuminate\\Database\\Connection->affectingStatement('update `plugin_...', Array)
#3 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2721): Illuminate\\Database\\Connection->update('update `plugin_...', Array)
#4 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(820): Illuminate\\Database\\Query\\Builder->update(Array)
#5 C:\\xampp\\htdocs\\zc158\\includes\\classes\\PluginManager.php(192): Illuminate\\Database\\Eloquent\\Builder->update(Array)
#6 C:\\xampp\\htdocs\\zc158\\includes\\classes\\PluginManager.php(187): Zencart\\PluginManager\\PluginManager->updatePluginControl(Array)
#7 C:\\xampp\\htdocs\\zc158\\includes\\classes\\PluginManager.php(23): Zencart\\PluginManager\\PluginManager->updateDbPlugins(Array)
#8 C:\\xampp\\htdocs\\zc158\\app\\Providers\\AppServiceProvider.php(45): Zencart\\PluginManager\\PluginManager->inspectAndUpdate()
#9 [internal function]: App\\Providers\\AppServiceProvider->boot()
#10 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(32): call_user_func_array(Array, Array)
#11 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(827): Illuminate\\Container\\Container->call(Array)
#15 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(810): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\AppServiceProvider))
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\AppServiceProvider), 17)
#17 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(811): array_walk(Array, Object(Closure))
#18 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(210): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#20 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#21 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#22 C:\\xampp\\htdocs\\zc158\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#23 C:\\xampp\\htdocs\\zc158\\includes\\illuminate_bootstrap.php(10): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#24 C:\\xampp\\htdocs\\zc158\\includes\\application_top.php(186): require('C:\\\\xampp\\\\htdocs...')
#25 C:\\xampp\\htdocs\\zc158\\index.php(25): require('C:\\\\xampp\\\\htdocs...')
#26 {main}
"} 
```

**Comment by drbyte** [comment]
I'm not sure I have an answer, as I can't duplicate the situation, but I do wonder if either of the following (or the combination of both) are related.

> #24 C:\\xampp\\htdocs\\zc158\\includes\\application_top.php(186): require('C:\\\\xampp\\\\htdocs...')
#25 C:\\xampp\\htdocs\\zc158\\index.php(25): require('C:\\\\xampp\\\\htdocs...')

Something about the quadruple-backslashes feels wrong here.

> PDOException(code: 0): could not find driver at ...\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php:70

The Laravel database connector uses `PDO`, which normally comes precompiled into PHP. 
In the `app\config\database.php` file we set the connector to `DB_TYPE` which should be `mysql` in your configure.php file. Then that connection's settings sub-array later in that file uses the other DB_xxxxxx stuff also from configure.php.

I wonder if the extra backslashes are causing any misinterpretation of files? 
Or what the configure.php content is that might be different than expected.

**Comment by netcrop** [comment]
I just made a fresh install for zc158 using LAMP (linux+apache+mariadb+php) stack without this issue. I think this issue might be related to the XAMPP stack. Due to xampp added another layer upon LAMP or WAMP.

**Comment by lat9** [comment]
I've got a special XAMPP setup, using the mechanism described [here](https://stackoverflow.com/questions/45790160/is-there-way-to-use-two-php-versions-in-xampp).  I believe that the issue might be in that usage.

Essentially, I've got a base install using PHP 7.3 with other PHP versions installed separately.  When I'm accessing PHP 7.3, I use `localhost/zc158` to access; for PHP 7.4 (or 7.1 or 5.6), I use `localhost:80vv/zc158` (where _vv_ is the PHP version number.

When I make the access without the port, i.e. PHP 7.3, all's good.  When I make the access with a port, e.g. `localhost:8074/zc158`, all goes to heck.  PHP 7.1 experiences a different, but fatal, error than 7.4 but neither work.  Could the inclusion of that port be causing Laravel to throw these hairballs?

**Comment by lat9** [comment]
OK, my PHP 7.4 installation didn't have `pdo_mysql` included.  I've got that included and now receive the following:
```
[04-Aug-2020 11:04:29 UTC] PHP Fatal error:  Declaration of Symfony\Component\Translation\TranslatorInterface::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale) in C:\xampp\htdocs\zc158\app\vendor\symfony\translation\TranslatorInterface.php on line 24
```

**Comment by lat9** [comment]
Following up.  I've reworked the `php.ini` for my PHP 7.4 installation and all's better again (using the now-current repository's file-set).
