### ISSUE TITLE
ZC158, request to bogus login.css made when zc_plugins enabled

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4375]
install/enable displaylogs plugin.
This install process has a bug in it, 
https://github.com/zencart/zencart/issues/4270
but does work subsequently.

On the login screen, there is now a request for a non-existent login.css file:
![Clipboard01](https://user-images.githubusercontent.com/4391026/121746346-0dff2780-cb06-11eb-9e3c-2241a028c2d5.gif)

If the plugin is uninstalled, the request is not made.

**Comment by proseLA** [comment]
i think the problem is here:

https://github.com/zencart/zencart/blob/aea6791602c4a5b69823c99367ec5f4c314643c1/admin/includes/admin_html_head.php#L47-L50

and _**might**_ be corrected with this on line 47:
```
if (file_exists($absoluteDir . substr($relativeDir, 1) . 'admin/includes/css/' . basename($PHP_SELF, '.php') . '.css')) {
```

that said,  problems on the plugin manager: admin/index.php?cmd=plugin_manager

```
[11-Jun-2021 23:25:44 America/Los_Angeles] Request URI: /admin/index.php?cmd=plugin_manager, IP address: 0.0.0.0
#1  call_user_func() called at [/var/www/zcdev/laravel/vendor/illuminate/pagination/AbstractPaginator.php:532]
#2  Illuminate\Pagination\AbstractPaginator::viewFactory() called at [/var/www/zcdev/laravel/vendor/illuminate/pagination/LengthAwarePaginator.php:91]
#3  Illuminate\Pagination\LengthAwarePaginator->render() called at [/var/www/zcdev/laravel/vendor/illuminate/pagination/LengthAwarePaginator.php:79]
#4  Illuminate\Pagination\LengthAwarePaginator->links() called at [/var/www/zcdev/admin/includes/templates/table_view.php:74]
#5  require(/var/www/zcdev/admin/includes/templates/table_view.php) called at [/var/www/zcdev/admin/plugin_manager.php:104]
#6  require(/var/www/zcdev/admin/plugin_manager.php) called at [/var/www/zcdev/admin/index.php:11]
--> PHP Warning: call_user_func() expects parameter 1 to be a valid callback, no array or string given in /var/www/zcdev/laravel/vendor/illuminate/pagination/AbstractPaginator.php on line 532.

[11-Jun-2021 23:25:44 America/Los_Angeles] PHP Fatal error:  Uncaught Error: Call to a member function make() on null in /var/www/zcdev/laravel/vendor/illuminate/pagination/LengthAwarePaginator.php:91
Stack trace:
#0 /var/www/zcdev/laravel/vendor/illuminate/pagination/LengthAwarePaginator.php(79): Illuminate\Pagination\LengthAwarePaginator->render(NULL, Array)
#1 /var/www/zcdev/admin/includes/templates/table_view.php(74): Illuminate\Pagination\LengthAwarePaginator->links()
#2 /var/www/zcdev/admin/plugin_manager.php(104): require('/var/www/zcdev/...')
#3 /var/www/zcdev/admin/index.php(11): require('/var/www/zcdev/...')
#4 {main}
  thrown in /var/www/zcdev/laravel/vendor/illuminate/pagination/LengthAwarePaginator.php on line 91
```

**Comment by scottcwilson** [comment]
Can this be closed?

**Comment by proseLA** [comment]
i am not able to reproduce the bug.  i would say it is @torvista 's call on it.
