### ISSUE TITLE
After install can not load store if DB_PREFIX used

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#4404]
Did a complete fresh install today of ZC 1.5.8 to a php 8.0 system, new database, new database user, new server user, new folder(s), etc... New sub-domain. Store installed to the root of the sub-domain. No additional software installed. Database demo selected for incorporation.

I've tried multiple database prefixes to determine if the content of the prefix mattered and to reproduce this problem it does not matter, any prefix will cause the store not to load and a 500 error to be issued.

May I also add that the ZC admin developers tool kit debug tools now appear to be useless at least in investigating this issue.

Debug log generated is similar to below:
Note, I have replaced details in some cases, but left the "traceable" information. For example, whatever value exists for `DB_PREFIX` in `includes/configure.php` that is what is substituted in below content. PHP error messages truncate the content on the "right" side, so a five character length `DB_PREFIX` will have the first seven characters displayed. I was able to output the sql statement that is/was generated and it completely contained the `DB_PREFIX` being listed twice in a row.
````php
[Date Time TimeZone] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB_DATABASE.DB_PREFIXDB_PREFIXplugin_control' doesn't exist in /serverpath/laravel/vendor/illuminate/database/Connection.php:492
Stack trace:
#0 /serverpath/laravel/vendor/illuminate/database/Connection.php(492): PDO->prepare('update `DB_PREFIXDB_PREFIX...')
#1 /serverpath/laravel/vendor/illuminate/database/Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}('update `DB_PREFIXDB_PREFIX...', Array)
#2 /serverpath/laravel/vendor/illuminate/database/Connection.php(638): Illuminate\Database\Connection->runQueryCallback('update `DB_PREFIXDB_PREFIX...', Array, Object(Closure))
#3 /serverpath/laravel/vendor/illuminate/database/Connection.php(503): Illuminate\Database\Connection->run('update `DB_PREFIXDB_PREFIX...', Array, Object(Closure))
#4 /serverpath/laravel/vendor/illuminate/database/Connection.php(436): Illuminate\Database\Connection->affectingStatement('update `DB_PREFIXDB_PREFIX...', Array)
#5 /serverpath/laravel/vendor/illuminate/database/Query/Builder.php(2913): Illuminate\Database\Connection->update('update `DB_PREFIXDB_PREFIX...', Array)
#6 /serverpath/laravel/vendor/illuminate/database/Eloquent/Builder.php(841): Illuminate\Database\Query\Builder->update(Array)
#7 /serverpath/includes/classes/PluginManager.php(192): Illuminate\Database\Eloquent\Builder->update(Array)
#8 /serverpath/includes/classes/PluginManager.php(187): Zencart\PluginManager\PluginManager->updatePluginControl(Array)
#9 /serverpath/includes/classes/PluginManager.php(23): Zencart\PluginManager\PluginManager->updateDbPlugins(Array)
#10 /serverpath/includes/application_top.php(214): Zencart\PluginManager\PluginManager->inspectAndUpdate()
#11 /serverpath/index.php(25): require('/serverpath...')
#12 {main}
````

The "kicker" to this? I was installing a version of Zen Cart for testing a simple plugin and happened to realize that it was the 1.5.8 version, so thought I would move forwards with it considering it was my first time testing out 1.5.8. Had problems with the base install process as well, but will address that separately. 

Trying to chase this down even using some of the above information is anything but easy these days, also it seems that much of the associated files are not in the search tool as I can not find how the database table `plugin_control` is even being considered for review/update. Searching the catalog/admin for `plugin_control` returned basically two results with information from the catalog:
````php
<!--StartFragment-->

/serverpath/includes/database_tables.php
--
Line # 71 : define('TABLE_PAYPAL_SESSION', DB_PREFIX . 'paypal_session');
Line # 72 : define('TABLE_PAYPAL_PAYMENT_STATUS', DB_PREFIX . 'paypal_payment_status');
Line # 73 : define('TABLE_PAYPAL_PAYMENT_STATUS_HISTORY', DB_PREFIX . 'paypal_payment_status_history');
Line # 74 : define('TABLE_PLUGIN_CONTROL', DB_PREFIX . 'plugin_control');
Line # 75 : define('TABLE_PLUGIN_CONTROL_VERSIONS', DB_PREFIX . 'plugin_control_versions');
Line # 76 : define('TABLE_PLUGIN_GROUPS', DB_PREFIX . 'plugin_groups');
Line # 77 : define('TABLE_PLUGIN_GROUPS_DESCRIPTION', DB_PREFIX . 'plugin_groups_description');
Line # 72 : define('TABLE_PAYPAL_PAYMENT_STATUS', DB_PREFIX . 'paypal_payment_status');
Line # 73 : define('TABLE_PAYPAL_PAYMENT_STATUS_HISTORY', DB_PREFIX . 'paypal_payment_status_history');
Line # 74 : define('TABLE_PLUGIN_CONTROL', DB_PREFIX . 'plugin_control');
Line # 75 : define('TABLE_PLUGIN_CONTROL_VERSIONS', DB_PREFIX . 'plugin_control_versions');
Line # 76 : define('TABLE_PLUGIN_GROUPS', DB_PREFIX . 'plugin_groups');
Line # 77 : define('TABLE_PLUGIN_GROUPS_DESCRIPTION', DB_PREFIX . 'plugin_groups_description');
Line # 78 : define('TABLE_PRODUCTS', DB_PREFIX . 'products');

<!--EndFragment-->

<!--StartFragment-->

/serverpath/includes/classes/PluginSupport/BasePluginInstaller.php
--
Line #67 :
Line #68 :     protected function setPluginVersionStatus($pluginKey, $version, $status)
Line #69 :     {
Line #70 :         $sql = "UPDATE " . TABLE_PLUGIN_CONTROL . " SET status = :status:, version = :version: WHERE unique_key = :uniqueKey:";
Line #71 :         $sql = $this->dbConn->bindVars($sql, ':status:', $status, 'integer');
Line #72 :         $sql = $this->dbConn->bindVars($sql, ':uniqueKey:', $pluginKey, 'string');
Line #73 :         $sql = $this->dbConn->bindVars($sql, ':version:', $version, 'string');

<!--EndFragment-->
````

For further information, I am able to do this "research" because I reinstalled using an empty database prefix as the admin was useless also so long as the database has/had a prefix. I still have 2 other attempted table installs in that database to which I can switch for testing/verification

**Comment by scottcwilson** [comment]
I have seen a situation in 1.5.7d where admin failed to load and gave error_71_maintenance_required.
This was fixed by changing admin/includes/init_includes/init_database.php to use === i.e.
```
  if ($result->RecordCount() === 0) {
```
Please try this on your setup.

**Comment by scottcwilson** [comment]
Reproduced.  

Suggested fixes: 
includes/application_top.php line 208 should be 
'prefix'    => '',

admin/includes/application_bootstrap.php line 192 should also be 
'prefix'    => '',

Needs more testing before I PR.
