### ISSUE TITLE
Installation zc_install/includes/nginx_conf/ directory needs to be writable for installation to succeed

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#4538]
**Describe the bug**
If zc_install/includes/nginx_conf/ is not writable installation fails with white screen.

**Version**
Zen Cart version: 1.5.8
PHP version: 8.0.14
MySQL version: mysqlnd 8.0.14
Plugins that may be related: None
What older/newer versions were also tested? no

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Vanilla installation

**Expected behavior**
Check to make sure directory is writable and if not prevent installation

**Debug/Error Logs**
[10-Jan-2022 15:28:54 UTC] PHP Warning:  fopen(includes/nginx_conf/zencart_ngx_server.conf): Failed to open stream: Permission denied in /home/lotus/public_html/innerlightcrystals/Test158/zc_install/includes/modules/pages/completion/header_php.php on line 62
[10-Jan-2022 15:28:54 UTC] PHP Stack trace:
[10-Jan-2022 15:28:54 UTC] PHP   1. {main}() /home/lotus/public_html/innerlightcrystals/Test158/zc_install/index.php:0
[10-Jan-2022 15:28:54 UTC] PHP   2. require() /home/lotus/public_html/innerlightcrystals/Test158/zc_install/index.php:40
[10-Jan-2022 15:28:54 UTC] PHP   3. fopen($filename = 'includes/nginx_conf/zencart_ngx_server.conf', $mode = 'w') /home/lotus/public_html/innerlightcrystals/Test158/zc_install/includes/modules/pages/completion/header_php.php:62
[10-Jan-2022 15:28:54 UTC] PHP Fatal error:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /home/lotus/public_html/innerlightcrystals/Test158/zc_install/includes/modules/pages/completion/header_php.php:63
Stack trace:
#0 /home/lotus/public_html/innerlightcrystals/Test158/zc_install/includes/modules/pages/completion/header_php.php(63): fwrite()
#1 /home/lotus/public_html/innerlightcrystals/Test158/zc_install/index.php(40): require('...')
#2 {main}
  thrown in /home/lotus/public_html/innerlightcrystals/Test158/zc_install/includes/modules/pages/completion/header_php.php on line 63
 
**Devices (please complete the following information):**
 - Operating System: Ubuntu 20.04.3 LTS 64 bit
 - Browser Firefox 95.01

**Comment by brittainmark** [comment]
suggest this is made a errorLevel: FAIL as causes white screen.
or change code in header.php line 62-64 to catch error and fail gracefully
`$fh = fopen($ngx_output_file, "w");
  fwrite($fh, $ngx_content);
  fclose($fh);`

**Comment by brittainmark** [comment]
Another alternative is to move the NGINX configuration file to be written in the log Directory. This assumes that there is nothing in the config file that will jeopardize the integrity/security of the site.

If you want, I can do this (above) or modify systemChecksl.yml and main.php to add a check.

**Comment by scottcwilson** [comment]
Rather not have config in the log folder but other ideas seem very good.  PR please.
