### ISSUE TITLE
Debug logs thrown for plugin manager, after initial zc158 installation

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4683]
**Describe the bug**
Initial installation of the zc158 branch (20220308, around 9am EST).  Log into the admin, go to Modules :: Plugin Manager to enable the "Display Logs" plugin.  Received multiple debugs, one on initial display and one once the plugin was enabled.

**Version**
Zen Cart version: zc158
PHP version: 7.4

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Fresh install of current zc158 branch
2. Click on Configuration :: Logging, enable all logging.
3. Click on Modules :: Plugin Manager
4. Install the "Display Log Files" plugin

**Expected behavior**
No debug logs should be generated.

**Debug/Error Logs**

On initial display of the plugin manager:
```
[08-Mar-2022 14:47:12 UTC] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=plugin_manager, IP address: 127.0.0.1
#1 call_user_func() called at [C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\AbstractPaginator.php:532]
#2 Illuminate\Pagination\AbstractPaginator::viewFactory() called at [C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:91]
#3 Illuminate\Pagination\LengthAwarePaginator->render() called at [C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:79]
#4 Illuminate\Pagination\LengthAwarePaginator->links() called at [C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php:74]
#5 require(C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php) called at [C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php:104]
#6 require(C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php) called at [C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php:11]
--> PHP Warning: call_user_func() expects parameter 1 to be a valid callback, no array or string given in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\AbstractPaginator.php on line 532.

[08-Mar-2022 14:47:12 UTC] PHP Fatal error: Uncaught Error: Call to a member function make() on null in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:91
Stack trace:
#0 C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php(79): Illuminate\Pagination\LengthAwarePaginator->render(NULL, Array)
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php(74): Illuminate\Pagination\LengthAwarePaginator->links()
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php(104): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
#4 {main}
thrown in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php on line 91

[08-Mar-2022 14:47:12 UTC] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=plugin_manager, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught Error: Call to a member function make() on null in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:91
Stack trace:
#0 C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php(79): Illuminate\Pagination\LengthAwarePaginator->render(NULL, Array)
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php(74): Illuminate\Pagination\LengthAwarePaginator->links()
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php(104): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
#4 {main}
thrown in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php on line 91.
```

Clicking on the "Install" button:
```
[08-Mar-2022 14:47:15 UTC] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=plugin_manager&page=1&colKey=DisplayLogs&action=install, IP address: 127.0.0.1
#1 call_user_func() called at [C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\AbstractPaginator.php:532]
#2 Illuminate\Pagination\AbstractPaginator::viewFactory() called at [C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:91]
#3 Illuminate\Pagination\LengthAwarePaginator->render() called at [C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:79]
#4 Illuminate\Pagination\LengthAwarePaginator->links() called at [C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php:74]
#5 require(C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php) called at [C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php:104]
#6 require(C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php) called at [C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php:11]
--> PHP Warning: call_user_func() expects parameter 1 to be a valid callback, no array or string given in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\AbstractPaginator.php on line 532.

[08-Mar-2022 14:47:15 UTC] PHP Fatal error: Uncaught Error: Call to a member function make() on null in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:91
Stack trace:
#0 C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php(79): Illuminate\Pagination\LengthAwarePaginator->render(NULL, Array)
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php(74): Illuminate\Pagination\LengthAwarePaginator->links()
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php(104): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
#4 {main}
thrown in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php on line 91

[08-Mar-2022 14:47:15 UTC] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=plugin_manager&page=1&colKey=DisplayLogs&action=install, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught Error: Call to a member function make() on null in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:91
Stack trace:
#0 C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php(79): Illuminate\Pagination\LengthAwarePaginator->render(NULL, Array)
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php(74): Illuminate\Pagination\LengthAwarePaginator->links()
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php(104): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
#4 {main}
thrown in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php on line 91.
```

Once the install of the plugin is complete:
```
[08-Mar-2022 14:47:17 UTC] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=plugin_manager&page=1&colKey=DisplayLogs, IP address: 127.0.0.1
#1 call_user_func() called at [C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\AbstractPaginator.php:532]
#2 Illuminate\Pagination\AbstractPaginator::viewFactory() called at [C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:91]
#3 Illuminate\Pagination\LengthAwarePaginator->render() called at [C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:79]
#4 Illuminate\Pagination\LengthAwarePaginator->links() called at [C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php:74]
#5 require(C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php) called at [C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php:104]
#6 require(C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php) called at [C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php:11]
--> PHP Warning: call_user_func() expects parameter 1 to be a valid callback, no array or string given in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\AbstractPaginator.php on line 532.

[08-Mar-2022 14:47:17 UTC] PHP Fatal error: Uncaught Error: Call to a member function make() on null in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:91
Stack trace:
#0 C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php(79): Illuminate\Pagination\LengthAwarePaginator->render(NULL, Array)
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php(74): Illuminate\Pagination\LengthAwarePaginator->links()
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php(104): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
#4 {main}
thrown in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php on line 91

[08-Mar-2022 14:47:17 UTC] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=plugin_manager&page=1&colKey=DisplayLogs, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught Error: Call to a member function make() on null in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php:91
Stack trace:
#0 C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php(79): Illuminate\Pagination\LengthAwarePaginator->render(NULL, Array)
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\templates\table_view.php(74): Illuminate\Pagination\LengthAwarePaginator->links()
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\plugin_manager.php(104): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
#4 {main}
thrown in C:\xampp\htdocs\zc158\laravel\vendor\illuminate\pagination\LengthAwarePaginator.php on line 91.
```

**Comment by torvista** [comment]
https://github.com/zencart/zencart/issues/4270
