### ISSUE TITLE
zc158: PHP Fatal error when setting SHOW_CREATE_ACCOUNT_DEFAULT_COUNTRY to 'None'

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4734]
Navigate to the admin's `Configuration :: Customer Details` and set **Create Account Default Country ID** to _None_.  You'll be met with a partial whitescreen and an accompanied error log similar to:
```
[16-Apr-2022 15:52:26 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to zen_get_countries() must be of the type int, string given, called in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php on line 100 and defined in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php:50
Stack trace:
#0 C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php(100): zen_get_countries('', false, true)
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\functions\general.php(439): zen_get_country_name('')
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\configuration.php(145): zen_call_function('zen_get_country...', '')
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
#4 {main}
  thrown in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php on line 50

[16-Apr-2022 15:52:26 Europe/Berlin] Request URI: /zc158/hoisT-PYL-teAch/index.php?cmd=configuration&gID=5&cID=146, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught TypeError: Argument 1 passed to zen_get_countries() must be of the type int, string given, called in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php on line 100 and defined in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php:50
Stack trace:
#0 C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php(100): zen_get_countries('', false, true)
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\functions\general.php(439): zen_get_country_name('')
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\configuration.php(145): zen_call_function('zen_get_country...', '')
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
#4 {main}
  thrown in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php on line 50.
```

Further attempts to display that configuration page will be met with the same condition.  To patch yourself out (until the code correction is supplied), navigate to `Tools :: Install SQL Patches` and enter:
```
UPDATE configuration SET configuration_value = 223 WHERE configuration_key = 'SHOW_CREATE_ACCOUNT_DEFAULT_COUNTRY';
```

**Comment by proseLA** [comment]
this can be addressed here:

https://github.com/zencart/zencart/blob/bc8913c99bb38e7291f5cf65383fd1c7526db938/includes/functions/functions_addresses.php#L20-L24

line 21:
```
'id' => 0,
```

which then necessitates this new notice to be addressed:
https://github.com/zencart/zencart/blob/bc8913c99bb38e7291f5cf65383fd1c7526db938/includes/functions/functions_addresses.php#L98-L102

line 101:
```
return $country_array['countries_name'] ?? 'none or some other constant';
```

i think all of this country processing could be refactored for easier reading.  i'm a bigger fan of putting it all into a class file.  and these pulldowns could extend the new pulldown class.  perhaps when more time exists....

**Comment by lat9** [comment]
Yep, as you indicated, it's the "tip of the iceberg".

**Comment by lat9** [comment]
I'm working on an overall update which will necessitate an addition to zc_install for existing stores that use "None".
