### ISSUE TITLE
zc158, PHP 8.1: Another PHP Deprecated log

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4797]
Seeing logs similar to
```
[12-May-2022 09:17:52 UTC] Request URI: /zc158/index.php?main_page=shopping_cart, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\functions\functions_general_shared.php(341): mt_srand()
#2 C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php(333): zen_rand()
#3 C:\xampp\htdocs\zc158\includes\modules\sideboxes\whats_new.php(24): queryFactory->ExecuteRandomMulti()
#4 C:\xampp\htdocs\zc158\includes\modules\column_left.php(30): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\zc158\includes\templates\responsive_classic\common\tpl_main_page.php(142): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\zc158\index.php(94): require('C:\\xampp\\htdocs...')
--> PHP Deprecated: Implicit conversion from float 254533.99999999997 to int loses precision in C:\xampp\htdocs\zc158\includes\functions\functions_general_shared.php on line 341.
```
Also seeing this on the 'shopping_cart' page.  That line, in the `zen_rand` function contains
```
        mt_srand((double)microtime() * 1000000);
```

Noting that the test site has `Configuration :: Logging :: Report All Errors (Store)` set to 'Yes' ... not sure if that setting is 'playing' with the issue or not.

**Comment by lat9** [comment]
That implicit conversion is based on the function's definition:
![image](https://user-images.githubusercontent.com/2685585/168052431-37356cda-5004-48fa-a844-7fc72aaecf7c.png)

**Comment by scottcwilson** [comment]
Link to doc:
https://www.php.net/manual/en/function.mt-srand.php
