### ISSUE TITLE
PHP Deprecation during checkout with attributed products, due to `NULL` fields

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4968]
A PHP Deprecated log is created during storefront processing when an order is placed for an attributed product that doesn't have any quantity-discounts applied (think the demo product "A Bug's Life "Multi Pak" Special 2003 Collectors Edition"), since `products_attributes::attributes_qty_prices` and `products_attributes::attributes_qty_prices_onetime` are (by default) NULL:
```
[01-Jul-2022 10:35:14 America/New_York] Request URI: /zc158/index.php?main_page=checkout_process, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php(175): mysqli_real_escape_string()
#2 C:\xampp\htdocs\zc158\includes\functions\database.php(104): queryFactory->prepare_input()
#3 C:\xampp\htdocs\zc158\includes\classes\order.php(1079): zen_db_perform()
#4 C:\xampp\htdocs\zc158\includes\modules\checkout_process.php(99): order->create_add_products()
#5 C:\xampp\htdocs\zc158\includes\modules\pages\checkout_process\header_php.php(14): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Deprecated: mysqli_real_escape_string(): Passing null to parameter #2 ($string) of type string is deprecated in C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php on line 175.
```

Separating out from #4963.

**Comment by scottcwilson** [comment]
This is with PHP 8.1?

**Comment by lat9** [comment]
Yes.
