### ISSUE TITLE
v158: PHP Fatal error for AJAX handlers that require languages

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4983]
If a plugin uses an AJAX handler and that AJAX handler requires language constants that are not present in the current language's main file (e.g. `/includes/languages/lang.english.php`), the language constants are not available and, when run under PHP 8.1+, results in a PHP fatal error, e.g. the following which results when attempting to use 'One-Page Checkout':
```
[03-Jul-2022 11:44:44 America/New_York] PHP Fatal error:  Uncaught Error: Undefined constant "TABLE_HEADING_PAYMENT_METHOD" in C:\xampp\htdocs\zc158\includes\templates\template_default\templates\tpl_modules_opc_payment_choices.php:21
Stack trace:
#0 C:\xampp\htdocs\zc158\includes\classes\ajax\zcAjaxOnePageCheckout.php(273): require()
#1 C:\xampp\htdocs\zc158\ajax.php(85): zcAjaxOnePageCheckout->updateShipping()
#2 {main}
  thrown in C:\xampp\htdocs\zc158\includes\templates\template_default\templates\tpl_modules_opc_payment_choices.php on line 21

[03-Jul-2022 11:44:44 America/New_York] Request URI: /zc158/ajax.php?act=ajaxOnePageCheckout&method=updateShipping, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught Error: Undefined constant "TABLE_HEADING_PAYMENT_METHOD" in C:\xampp\htdocs\zc158\includes\templates\template_default\templates\tpl_modules_opc_payment_choices.php:21
Stack trace:
#0 C:\xampp\htdocs\zc158\includes\classes\ajax\zcAjaxOnePageCheckout.php(273): require()
#1 C:\xampp\htdocs\zc158\ajax.php(85): zcAjaxOnePageCheckout->updateShipping()
#2 {main}
  thrown in C:\xampp\htdocs\zc158\includes\templates\template_default\templates\tpl_modules_opc_payment_choices.php on line 21.
```
The compatibility issue here is that the majority of the language-loading now happens during the page auto-loads' `init_templates.php` and `/includes/modules/require_languages.php` (which is used by that and other plugins) now just finalizes the language-loading done during that page-level initialization. 

Noting that the `ajax.php` requests are currently interpreted by the language-load process as one for the `index` page, since there is no `$_GET['main_page']` present.  The `zcAjaxOnePageCheckout.php` (as do other AJAX handlers) sets the value of `$_GET['main_page']`, `$current_page` and `$current_page_base` to reflect the page-related language file that should be loaded.

There needs to be some communication between the `ajax.php` processing and `require_languages.php` so that the language constants are properly loaded for the AJAX methods' use.

**Comment by lat9** [comment]
Noting that I believe that this issue will arise with the use of the `paypaldp.php` payment-method (or any other payment method that 'collectsCreditCartDataOnsite') that uses the standard 3-page checkout as well, as the `zcAjaxPayment.php` class performs a similar type operation.

**Comment by lat9** [comment]
Historically, for all previous versions of Zen Cart, the page-specific language files were loaded _after_ the auto-load process as part of the page header (e.g. `/includes/pages/contact_us/header_php.php`) or as part of an AJAX class' load via `/includes/modules/require_languages.php`.

The current storefront language-loading has migrated all language-file loads to the auto-load process, which is the source of this issue.
