### ISSUE TITLE
v158: paypalwpp, warnings and deprecations using Express Checkout button

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5055]
Base zc158 install, using responsive_classic template and PHP 8.1; demo products installed and paypalwpp installed and enabled.

Add an item to the cart, navigate to the shipping_cart and click the "Checkout with PayPal" button.  You're met with a whitescreen and logs similar to the following.  Note that line numbers are different as I've got a version of `paypalwpp` that's attempting to also address #4985.
```
[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1289): strpos()
#2 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1582): paypalwpp->getLineItemDetails()
#3 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php on line 1289.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1289): substr()
#2 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1582): paypalwpp->getLineItemDetails()
#3 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php on line 1289.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1570): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "shipping" in C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php on line 1570.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_gv.php(50): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\classes\order_total.php(49): ot_gv->__construct()
#2 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1574): order_total->__construct()
#3 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customer_id" in C:\xampp\htdocs\zc158\includes\modules\order_total\ot_gv.php on line 50.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(87): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(32): ot_group_pricing->calculate_deductions()
#2 C:\xampp\htdocs\zc158\includes\classes\order_total.php(179): ot_group_pricing->process()
#3 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1575): order_total->pre_confirmation_check()
#4 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customer_id" in C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php on line 87.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(88): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(32): ot_group_pricing->calculate_deductions()
#2 C:\xampp\htdocs\zc158\includes\classes\order_total.php(179): ot_group_pricing->process()
#3 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1575): order_total->pre_confirmation_check()
#4 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customers_group_pricing" in C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php on line 88.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(90): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(32): ot_group_pricing->calculate_deductions()
#2 C:\xampp\htdocs\zc158\includes\classes\order_total.php(179): ot_group_pricing->process()
#3 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1575): order_total->pre_confirmation_check()
#4 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customers_group_pricing" in C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php on line 90.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(92): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(32): ot_group_pricing->calculate_deductions()
#2 C:\xampp\htdocs\zc158\includes\classes\order_total.php(179): ot_group_pricing->process()
#3 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1575): order_total->pre_confirmation_check()
#4 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "group_percentage" in C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php on line 92.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(87): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(32): ot_group_pricing->calculate_deductions()
#2 C:\xampp\htdocs\zc158\includes\classes\order_total.php(63): ot_group_pricing->process()
#3 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1576): order_total->process()
#4 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customer_id" in C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php on line 87.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(88): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(32): ot_group_pricing->calculate_deductions()
#2 C:\xampp\htdocs\zc158\includes\classes\order_total.php(63): ot_group_pricing->process()
#3 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1576): order_total->process()
#4 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customers_group_pricing" in C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php on line 88.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(90): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(32): ot_group_pricing->calculate_deductions()
#2 C:\xampp\htdocs\zc158\includes\classes\order_total.php(63): ot_group_pricing->process()
#3 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1576): order_total->process()
#4 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "customers_group_pricing" in C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php on line 90.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(92): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php(32): ot_group_pricing->calculate_deductions()
#2 C:\xampp\htdocs\zc158\includes\classes\order_total.php(63): ot_group_pricing->process()
#3 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1576): order_total->process()
#4 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "group_percentage" in C:\xampp\htdocs\zc158\includes\modules\order_total\ot_group_pricing.php on line 92.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1289): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1582): paypalwpp->getLineItemDetails()
#2 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "shipping" in C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php on line 1289.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1289): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1582): paypalwpp->getLineItemDetails()
#2 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Trying to access array offset on value of type null in C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php on line 1289.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1289): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1582): paypalwpp->getLineItemDetails()
#2 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "shipping" in C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php on line 1289.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1289): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1582): paypalwpp->getLineItemDetails()
#2 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Trying to access array offset on value of type null in C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php on line 1289.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1120): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1589): paypalwpp->getLanguageCode()
#2 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Undefined array key "country" in C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php on line 1120.

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1120): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1589): paypalwpp->getLanguageCode()
#2 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Warning: Trying to access array offset on value of type null in C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php on line 1120.

[26-Jul-2022 12:30:14 America/New_York] PHP Fatal error:  Uncaught TypeError: zen_get_countries(): Argument #1 ($country_id) must be of type int, null given, called in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php on line 112 and defined in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php:50
Stack trace:
#0 C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php(112): zen_get_countries(NULL, true, true)
#1 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1120): zen_get_countries_with_iso_codes(NULL)
#2 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1589): paypalwpp->getLanguageCode()
#3 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
#4 {main}
  thrown in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php on line 50

[26-Jul-2022 12:30:14 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught TypeError: zen_get_countries(): Argument #1 ($country_id) must be of type int, null given, called in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php on line 112 and defined in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php:50
Stack trace:
#0 C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php(112): zen_get_countries(NULL, true, true)
#1 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1120): zen_get_countries_with_iso_codes(NULL)
#2 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1589): paypalwpp->getLanguageCode()
#3 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
#4 {main}
  thrown in C:\xampp\htdocs\zc158\includes\functions\functions_addresses.php on line 50.

```

**Comment by lat9** [comment]
Noting that this also gives the `freeoptions` shipping-module a hissy-fit, resulting in a PHP error during the process, too:
```
[26-Jul-2022 12:39:28 America/New_York] Request URI: /zc158/ipn_main_handler.php?type=ec, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php(665): trigger_error()
#2 C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php(632): queryFactory->show_error()
#3 C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php(273): queryFactory->set_error()
#4 C:\xampp\htdocs\zc158\includes\modules\shipping\freeoptions.php(54): queryFactory->Execute()
#5 C:\xampp\htdocs\zc158\includes\modules\shipping\freeoptions.php(35): freeoptions->update_status()
#6 C:\xampp\htdocs\zc158\includes\classes\shipping.php(77): freeoptions->__construct()
#7 C:\xampp\htdocs\zc158\includes\modules\payment\paypalwpp.php(1570): shipping->__construct()
#8 C:\xampp\htdocs\zc158\ipn_main_handler.php(75): paypalwpp->ec_step1()
--> PHP Fatal error: 1064:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY zone_id' at line 5 :: SELECT zone_id
                   FROM zones_to_geo_zones
                  WHERE geo_zone_id = 2
                    AND zone_country_id = 
                  ORDER BY zone_id ==> (as called by) C:\xampp\htdocs\zc158\includes\modules\shipping\freeoptions.php on line 54 <== in C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php on line 665.
```
