### ISSUE TITLE
Undefined array key "payment" new address 

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#5206]
**Describe the bug**
A warning log is created if you create a new address in the checkout process

**Version**
Zen Cart version: 1.5.8
PHP version: 8.0

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Login or Create an account and login to storefront
3. Add item to cart
4. Proceed to checkout
5. Select change address
6. Create a new address
7. warning log is produced when you return to the checkout step 1 screen

**Expected behavior**
no log file created

**Debug/Error Logs**
```
[07-Sep-2022 15:32:36 UTC] Request URI: /Test158/index.php?main_page=checkout_payment_address, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/checkout_new_address.php(181): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/pages/checkout_payment_address/header_php.php(33): require('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/index.php(35): require('...')
--> PHP Warning: Undefined array key "payment" in /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/checkout_new_address.php on line 181.
```

**Comment by brittainmark** [comment]
Part of #5103
