### ISSUE TITLE
PHP8.1 Square vendor modules not 8.1 compliant

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#5311]
**Describe the bug**
depreciated log produced for square this is actually an 8.1 issue

**Version**
Zen Cart version: 1.5.8
PHP version: 8.2,8.1
MySQL version: 

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. admin>modules>payment
2. depreciated log produced.

**Expected behavior**
no log produced

**Screenshots**
If applicable, add screenshots to help explain.

**Debug/Error Logs**
```
[11-Oct-2022 15:55:02 UTC] Request URI: /Test158/ADMIN/index.php?cmd=modules&set=payment, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/lib/Model/CreatePaymentRequest.php(20): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/autoload.php(39): require('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/square_support/ZenCartConnectCreatePaymentRequest.php(22): square->{closure}()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/square.php(81): require_once('...')
#4 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/modules.php(187): square->__construct()
#5 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/index.php(11): require('...')
--> PHP Deprecated: Return type of SquareConnect\Model\CreatePaymentRequest::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/lib/Model/CreatePaymentRequest.php on line 659.

[11-Oct-2022 15:55:02 UTC] Request URI: /Test158/ADMIN/index.php?cmd=modules&set=payment, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/lib/Model/CreatePaymentRequest.php(20): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/autoload.php(39): require('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/square_support/ZenCartConnectCreatePaymentRequest.php(22): square->{closure}()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/square.php(81): require_once('...')
#4 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/modules.php(187): square->__construct()
#5 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/index.php(11): require('...')
--> PHP Deprecated: Return type of SquareConnect\Model\CreatePaymentRequest::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/lib/Model/CreatePaymentRequest.php on line 669.

[11-Oct-2022 15:55:02 UTC] Request URI: /Test158/ADMIN/index.php?cmd=modules&set=payment, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/lib/Model/CreatePaymentRequest.php(20): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/autoload.php(39): require('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/square_support/ZenCartConnectCreatePaymentRequest.php(22): square->{closure}()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/square.php(81): require_once('...')
#4 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/modules.php(187): square->__construct()
#5 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/index.php(11): require('...')
--> PHP Deprecated: Return type of SquareConnect\Model\CreatePaymentRequest::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/lib/Model/CreatePaymentRequest.php on line 680.

[11-Oct-2022 15:55:02 UTC] Request URI: /Test158/ADMIN/index.php?cmd=modules&set=payment, IP address: 127.0.0.1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/lib/Model/CreatePaymentRequest.php(20): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/autoload.php(39): require('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/square_support/ZenCartConnectCreatePaymentRequest.php(22): square->{closure}()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/modules/payment/square.php(81): require_once('...')
#4 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/modules.php(187): square->__construct()
#5 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/index.php(11): require('...')
--> PHP Deprecated: Return type of SquareConnect\Model\CreatePaymentRequest::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/vendors/square/connect/lib/Model/CreatePaymentRequest.php on line 690.
```

**Additional context**
As these are Vendor supplied. I have done nothing with them. Especially as square is supposed to be removed from 1.5.8.
Either that or need to get a later and hopefully php8.1 compliant set of vendor files.

**Comment by brittainmark** [comment]
This is actually a php8.1 issue. It can be solved by adding
`#[\ReturnTypeWillChange]` to 
includes\classes\vendors\square\connect\lib\Model\CreatePaymentRequest.php

**Comment by brittainmark** [comment]
Can pr if you want.

**Comment by scottcwilson** [comment]
please do TY

**Comment by lat9** [comment]
I'm pretty sure that that construct is going to make PHP 7.4 and PHP 8.0 barf.

**Comment by brittainmark** [comment]
Check against 7.4 and fine.

**Comment by lat9** [comment]
Thanks, @brittainmark.
