### ISSUE TITLE
Fatal error with search using two keywords

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5571]
ZC158 admin/catalog, occuring since recent changes to search function.
One keyword ok, two keywords not ok

>/zencart/index.php?.main_page=search_result&search_in_description=1&keyword=key1+key2, IP address: 127.0.0.1, Language id 1
> #0 [internal function]: zen_debug_error_handler()
> #1 D:\Github\zencart\includes\classes\db\mysql\query_factory.php(667): trigger_error()
> #2 D:\Github\zencart\includes\classes\db\mysql\query_factory.php(634): queryFactory->show_error()
> #3 D:\Github\zencart\includes\classes\db\mysql\query_factory.php(275): queryFactory->set_error()
> #4 D:\Github\zencart\includes\classes\split_page_results.php(105): queryFactory->Execute()
> #5 D:\Github\zencart\includes\modules\pages\search_result\header_php.php(459): splitPageResults->__construct()
> #6 D:\Github\zencart\index.php(35): require('D:\\Github\\zenca...')
> --> PHP Fatal error: 1064:You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OR  pd.products_name LIKE '%key2%' OR  p.products_model LIKE '%key2%' OR  m.m...' at line 1 :: select count(distinct p.products_id) as total  FROM (products p              LEFT JOIN manufacturers m              USING(manufacturers_id), products_description pd, categories c, products_to_categories p2c ) LEFT JOIN meta_tags_products_description mtpd             ON (mtpd.products_id= p2c.products_id AND mtpd.language_id = 1) WHERE (p.products_status = 1                AND p.products_id = pd.products_id                AND pd.language_id = 1                AND p.products_id = p2c.products_id                AND p2c.categories_id = c.categories_id  AND ( (  pd.products_name LIKE '%key1%' OR  p.products_model LIKE '%key1%' OR  m.manufacturers_name LIKE '%key1%' OR  mtpd.metatags_keywords LIKE '%key1%' OR  mtpd.metatags_description LIKE '%key1%' OR  pd.products_description LIKE '%key1%')  AND  ( OR  pd.products_name LIKE '%key2%' OR  p.products_model LIKE '%key2%' OR  m.manufacturers_name LIKE '%key2%' OR  mtpd.metatags_keywords LIKE '%key2%' OR  mtpd.metatags_description LIKE '%key2%' OR  pd.products_description LIKE '%key2%')  )) ==> (as called by) D:\Github\zencart\includes\classes\split_page_results.php on line 105 <== in D:\Github\zencart\includes\classes\db\mysql\query_factory.php on line 667.

**Comment by torvista** [comment]
reverting this fixes it
https://github.com/zencart/zencart/pull/5569
