### ISSUE TITLE
Admin `orders.php` runs out of memory when displaying 70 orders/page

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5581]
Just upgrading a site from zc156b.  The site's set to display **70** orders per page.  Clicking on an order's table-row to display the order results in an out-of-memory condition.  Clicking on the "Details" button allows the order to be displayed.

I'll be doing some further investigation tomorrow.  FWIW, the site's got 100K+ orders currently recorded.

Noting that the out-of-memory log is created just after a MySQL fatal error:
```
[06-Feb-2023 03:18:58 UTC] Request URI: /admin/index.php?cmd=orders&page=1&oID=123653, IP address: xx.xx.xx.xx, Language id 1
#0 [internal function]: zen_debug_error_handler()
#1 /includes/classes/db/mysql/query_factory.php(667): trigger_error()
#2 /includes/classes/db/mysql/query_factory.php(634): queryFactory->show_error()
#3 /includes/classes/db/mysql/query_factory.php(275): queryFactory->set_error()
#4 /includes/functions/sessions.php(77): queryFactory->Execute()
#5 [internal function]: _sess_write()
#6 [internal function]: session_write_close()
--> PHP Fatal error: 2014:Commands out of sync; you can't run this command now :: insert into sessions (sesskey, expiry, `value`)
values ('16cbc18c6289eb74366bdd2c1f8d4a96', 1675683538, 'c2VjdXJpdHlUb2tlbnxzOjMyOiJhNDA3NDYwNTRjMWFlZjU5Mjk2MWQxMzI3ZTY0ODBhMCI7bGFuZ3VhZ2V8czo3OiJlbmdsaXNoIjtsYW5ndWFnZXNfaWR8aToxO2xhbmd1YWdlc19jb2RlfHM6MjoiZW4iO3NlbGVjdGVkX2JveHxzOjEzOiJjb25maWd1cmF0aW9uIjtodG1sX2VkaXRvcl9wcmVmZXJlbmNlX3N0YXR1c3xzOjg6IkNLRURJVE9SIjthZG1pbl9pZHxzOjI6IjY0IjttZXNzYWdlVG9TdGFja3xzOjA6IiI7')
ON DUPLICATE KEY UPDATE `value`='c2VjdXJpdHlUb2tlbnxzOjMyOiJhNDA3NDYwNTRjMWFlZjU5Mjk2MWQxMzI3ZTY0ODBhMCI7bGFuZ3VhZ2V8czo3OiJlbmdsaXNoIjtsYW5ndWFnZXNfaWR8aToxO2xhbmd1YWdlc19jb2RlfHM6MjoiZW4iO3NlbGVjdGVkX2JveHxzOjEzOiJjb25maWd1cmF0aW9uIjtodG1sX2VkaXRvcl9wcmVmZXJlbmNlX3N0YXR1c3xzOjg6IkNLRURJVE9SIjthZG1pbl9pZHxzOjI6IjY0IjttZXNzYWdlVG9TdGFja3xzOjA6IiI7', expiry=1675683538 ==> (as called by) /includes/functions/sessions.php on line 77 <== in /includes/classes/db/mysql/query_factory.php on line 667.
```

**Comment by lat9** [comment]
The (test) site's PHP `memory_limit` was set to a woefully-low **32M**; updating to 128M (and eventually 512M for just-in-case) corrected the issue.
