### ISSUE TITLE
Warning created if Square files left on server and Square webPay installed

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#5640]
**Describe the bug**
Warning log file created.

**Version**
Zen Cart version: 1.5.8
PHP version: 8.1

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Go to admin>modules>payment

**Expected behavior**
no log file

**Screenshots**
If applicable, add screenshots to help explain.

**Debug/Error Logs**
```
[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(84): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_REFUND_TITLE already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 84.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(85): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_TRANSACTION_SUMMARY already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 85.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(86): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_REFUND already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 86.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(87): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_REFUND_AMOUNT_TEXT already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 87.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(88): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_TEXT_REFUND_CONFIRM_CHECK already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 88.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(89): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_REFUND_TEXT_COMMENTS already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 89.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(90): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_REFUND_DEFAULT_MESSAGE already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 90.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(91): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_REFUND_SUFFIX already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 91.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(92): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_REFUND_BUTTON_TEXT already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 92.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(93): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_CAPTURE_TITLE already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 93.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(94): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_CAPTURE already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 94.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(95): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_TEXT_CAPTURE_CONFIRM_CHECK already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 95.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(96): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_CAPTURE_TEXT_COMMENTS already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 96.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(97): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_CAPTURE_DEFAULT_MESSAGE already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 97.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(98): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_CAPTURE_SUFFIX already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 98.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(99): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_CAPTURE_BUTTON_TEXT already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 99.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(100): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_VOID_TITLE already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 100.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(101): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_VOID already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 101.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(102): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_TEXT_VOID_CONFIRM_CHECK already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 102.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(103): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_VOID_DEFAULT_MESSAGE already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 103.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(104): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_VOID_SUFFIX already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 104.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(105): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_VOID_BUTTON_TEXT already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 105.

[12-Mar-2023 08:05:30 UTC] Request URI: /Test158/Horse-ENN-qUill/index.php?cmd=modules&set=payment, IP address: 127.0.0.1, Language id 1
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php(106): zen_debug_error_handler()
#1 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(39): include_once('...')
#2 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/FilesLanguageLoader.php(22): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#3 /home/lotus/public_html/innerlightcrystals/Test158/includes/classes/ResourceLoaders/LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#4 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/modules.php(183): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#5 /home/lotus/public_html/innerlightcrystals/Test158/Horse-ENN-qUill/index.php(11): require('...')
--> PHP Warning: Constant MODULE_PAYMENT_SQUARE_ENTRY_VOID_TEXT_COMMENTS already defined in /home/lotus/public_html/innerlightcrystals/Test158/includes/languages/english/modules/payment/square_webPay.php on line 106.
```

**Additional context**
As Square is deprecated. have supplied fix for Square rather than square webPay.  fix #5638

**Comment by brittainmark** [comment]
closed as merged.
