### ISSUE TITLE
installer error:  Undefined constant "DIR_FS_CATALOG"

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5916]
php 8.2.8, local, Windows
Using fileset v200 01/08/2023
New install/not regenerating configs, installing demo products.

[02-Aug-2023 08:53:45 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "DIR_FS_CATALOG" in D:\GitHub\zencart\includes\classes\db\mysql\query_factory.php:677
Stack trace:
#0 D:\GitHub\zencart\includes\classes\db\mysql\query_factory.php(659): queryFactory->show_error()
#1 D:\GitHub\zencart\includes\classes\db\mysql\query_factory.php(299): queryFactory->set_error(1366, 'Incorrect strin...', true)
#2 D:\GitHub\zencart\zc_install\includes\classes\class.zcDatabaseInstaller.php(545): queryFactory->Execute('update configur...')
#3 D:\GitHub\zencart\zc_install\includes\modules\pages\completion\header_php.php(39): zcDatabaseInstaller->doCompletion(Array)
#4 D:\GitHub\zencart\zc_install\index.php(40): require('D:\\GitHub\\zenca...')
#5 {main}
  thrown in D:\GitHub\zencart\includes\classes\db\mysql\query_factory.php on line 677

**Comment by drbyte** [comment]
While the PR I've linked will fix the "undefined constant" error, it will not fix the fact that whatever you're trying to insert as dev settings is triggering db query failures

**Comment by torvista** [comment]
One item in define('DEVELOPER_CONFIGS', 
is 'STORE_NAME_ADDRESS'. 

Long ago when I was first flagging up problems I found due to mis-handling of multibyte/accented characters, I made a habit of always including a series of them (áéíóúñ) in the store address and other places to highlight such problems.

My reference/dev copy of localConfig.php is encoded in utf-8 for these characters.
I copied/merged my edits into the core localConfig which is ANSI.
So the installer choked on these characters until the file was re-encoded in utf-8.
