### ISSUE TITLE
Shipping/Payment language files in legacy format result in PHP Warnings

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5932]
If a site being upgraded has older language overrides for shipping and payment modules (I'm guessing order-totals, too), multiple PHP Warnings are issued for previously-defined constants.

For example, place a zc156-era `freeshipper.php` language file into the site's /languages/english/modules/shipping/YOUR_TEMPLATE:
```
<?php
/**
 * @package shipping_modules
 * @copyright Copyright 2003-2011 Zen Cart Development Team
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 * @version $Id: freeshipper.php 18697 2011-05-04 14:35:20Z wilt $
 */

define('MODULE_SHIPPING_FREESHIPPER_TEXT_TITLE', 'FREE SHIPPING!');
define('MODULE_SHIPPING_FREESHIPPER_TEXT_DESCRIPTION', 'FREE SHIPPING');
define('MODULE_SHIPPING_FREESHIPPER_TEXT_WAY', 'No Delivery Charge');
```

- Using the demo products, place a [Sample of Product Free Shipping Type [PFS] (index.php?main_page=product_free_shipping_info&cPath=64&products_id=172) into the cart and navigate to the shopping cart page.
- Use the shipping estimator to view the shipping cost.

You'll see a log similar to the following logged:
```
[13-Aug-2023 14:16:59 America/New_York] Request URI: /zc158/index.php?main_page=shopping_cart&search_in_description=1&keyword=free%20shipping&sort=20a, IP address: 127.0.0.1, Language id 1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\languages\english\modules\shipping\bootstrap\freeshipper.php(9): define()
#2 C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\FilesLanguageLoader.php(39): include_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\FilesLanguageLoader.php(20): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#4 C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#5 C:\xampp\htdocs\zc158\includes\classes\shipping.php(76): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#6 C:\xampp\htdocs\zc158\includes\modules\shipping_estimator.php(153): shipping->__construct()
#7 C:\xampp\htdocs\zc158\includes\templates\bootstrap\modalboxes\tpl_shipping_estimator.php(19): require('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\zc158\includes\templates\bootstrap\templates\tpl_shopping_cart_default.php(204): require('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\zc158\includes\templates\bootstrap\common\tpl_main_page.php(216): require('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\zc158\index.php(94): require('C:\\xampp\\htdocs...')
--> PHP Warning: Constant MODULE_SHIPPING_FREESHIPPER_TEXT_TITLE already defined in C:\xampp\htdocs\zc158\includes\languages\english\modules\shipping\bootstrap\freeshipper.php on line 9.

[13-Aug-2023 14:16:59 America/New_York] Request URI: /zc158/index.php?main_page=shopping_cart&search_in_description=1&keyword=free%20shipping&sort=20a, IP address: 127.0.0.1, Language id 1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\languages\english\modules\shipping\bootstrap\freeshipper.php(10): define()
#2 C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\FilesLanguageLoader.php(39): include_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\FilesLanguageLoader.php(20): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#4 C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#5 C:\xampp\htdocs\zc158\includes\classes\shipping.php(76): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#6 C:\xampp\htdocs\zc158\includes\modules\shipping_estimator.php(153): shipping->__construct()
#7 C:\xampp\htdocs\zc158\includes\templates\bootstrap\modalboxes\tpl_shipping_estimator.php(19): require('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\zc158\includes\templates\bootstrap\templates\tpl_shopping_cart_default.php(204): require('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\zc158\includes\templates\bootstrap\common\tpl_main_page.php(216): require('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\zc158\index.php(94): require('C:\\xampp\\htdocs...')
--> PHP Warning: Constant MODULE_SHIPPING_FREESHIPPER_TEXT_DESCRIPTION already defined in C:\xampp\htdocs\zc158\includes\languages\english\modules\shipping\bootstrap\freeshipper.php on line 10.

[13-Aug-2023 14:16:59 America/New_York] Request URI: /zc158/index.php?main_page=shopping_cart&search_in_description=1&keyword=free%20shipping&sort=20a, IP address: 127.0.0.1, Language id 1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\languages\english\modules\shipping\bootstrap\freeshipper.php(11): define()
#2 C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\FilesLanguageLoader.php(39): include_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\FilesLanguageLoader.php(20): Zencart\LanguageLoader\FilesLanguageLoader->loadFileDefineFile()
#4 C:\xampp\htdocs\zc158\includes\classes\ResourceLoaders\LanguageLoader.php(85): Zencart\LanguageLoader\FilesLanguageLoader->loadExtraLanguageFiles()
#5 C:\xampp\htdocs\zc158\includes\classes\shipping.php(76): Zencart\LanguageLoader\LanguageLoader->loadExtraLanguageFiles()
#6 C:\xampp\htdocs\zc158\includes\modules\shipping_estimator.php(153): shipping->__construct()
#7 C:\xampp\htdocs\zc158\includes\templates\bootstrap\modalboxes\tpl_shipping_estimator.php(19): require('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\zc158\includes\templates\bootstrap\templates\tpl_shopping_cart_default.php(204): require('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\zc158\includes\templates\bootstrap\common\tpl_main_page.php(216): require('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\zc158\index.php(94): require('C:\\xampp\\htdocs...')
--> PHP Warning: Constant MODULE_SHIPPING_FREESHIPPER_TEXT_WAY already defined in C:\xampp\htdocs\zc158\includes\languages\english\modules\shipping\bootstrap\freeshipper.php on line 11.
```

Shouldn't the `includes/languages/modules/*` template-override directories be loaded first so that these warnings don't get issued?

I'll note that a similar issue can be seen with the `payments` language overrides; haven't yet traversed to see if the `order_totals` experience the same issue, but I'm guessing so.

**Comment by scottcwilson** [comment]
If you are overriding a built in file, you *must* use the new format.   You can't just copy in an old file.

**Comment by scottcwilson** [comment]
"Core language files should be overridden in the new format; plugin language files may use the old or the new file format."

https://docs.zen-cart.com/user/upgrading/release_specific_upgrade_considerations/#zen-cart-158-and-zen-cart-158a

(bullet 5.  Yes, I know there's a typo in "overridden.")

**Comment by lat9** [comment]
I'll need to look (in the morning), since I _thought_ that a page's language file (like shopping_cart.php) doesn't result in those issues.

**Comment by lat9** [comment]
> I'll need to look (in the morning), since I _thought_ that a page's language file (like shopping_cart.php) doesn't result in those issues.

Morning, whatever, you're right that the same warning and non-override occurs on the page-related language files.  Please note that, IMO, that doesn't make it _right_ because it's a right PITA on upgrades.

The docs should be changed to read

"Core language files ~~should~~**must** be overridden in the new format _to prevent unwanted PHP Warnings_; plugin language files may use the old or the new file format."

**Comment by scottcwilson** [comment]
Will change on next checkin.

**Comment by lat9** [comment]
What we _really_ need is a **_reliable_** language-file converter.
