### ISSUE TITLE
Admin product-edit: Non-existent `pID` results in PHP Fatal error (PHP 8.2)

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#6025]
If a non-existent `pID` is supplied to an admin product-edit, a PHP Fatal error results:
```
[28-Oct-2023 13:25:06 UTC] PHP Fatal error:  Uncaught TypeError: zen_get_admin_module_from_directory(): Argument #1 ($product_type) must be of type int, string given, called in C:\xampp\htdocs\zc200w\admin200\product.php on line 90 and defined in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php:205
Stack trace:
#0 C:\xampp\htdocs\zc200w\admin200\product.php(90): zen_get_admin_module_from_directory('', 'collect_info.ph...')
#1 C:\xampp\htdocs\zc200w\admin200\index.php(11): require('C:\\xampp\\htdocs...')
#2 {main}
  thrown in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php on line 205

[28-Oct-2023 13:25:06 UTC] Request URI: /zc200w/admin200/index.php?cmd=product&product_type=&pID=1288&action=new_product, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught TypeError: zen_get_admin_module_from_directory(): Argument #1 ($product_type) must be of type int, string given, called in C:\xampp\htdocs\zc200w\admin200\product.php on line 90 and defined in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php:205
Stack trace:
#0 C:\xampp\htdocs\zc200w\admin200\product.php(90): zen_get_admin_module_from_directory('', 'collect_info.ph...')
#1 C:\xampp\htdocs\zc200w\admin200\index.php(11): require('C:\\xampp\\htdocs...')
#2 {main}
  thrown in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php on line 205.

[28-Oct-2023 13:25:06 UTC] Request URI: /zc200w/admin200/index.php?cmd=product&product_type=&pID=1288&action=new_product, IP address: 127.0.0.1
--> PHP Fatal error: Uncaught TypeError: zen_get_admin_module_from_directory(): Argument #1 ($product_type) must be of type int, string given, called in C:\xampp\htdocs\zc200w\admin200\product.php on line 90 and defined in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php:205
Stack trace:
#0 C:\xampp\htdocs\zc200w\admin200\product.php(90): zen_get_admin_module_from_directory('', 'collect_info.ph...')
#1 C:\xampp\htdocs\zc200w\admin200\index.php(11): require('C:\\xampp\\htdocs...')
#2 {main}
  thrown in C:\xampp\htdocs\zc200w\includes\functions\functions_files.php on line 205.
```

**Comment by drbyte** [comment]
On line 13 of `product.php` the call to `zen_get_products_type()` returns a blank string when an invalid pID is supplied.

That blank string is frequently passed to URLs ... implying a `0` which would also technically be invalid.

I'm inclined to give a notification and a redirect if the pID is invalid, rather than to merely bypass type-safety which would result in an empty product-edit form ... which would be confusing to the end-user.

Question: how is the admin getting a link to edit an invalid pID? Perhaps that root-cause should be addressed too?

**Comment by lat9** [comment]
Answer: A site-specific customization that enables the editing of products in the order (yeah, I know).  That root-cause will be addressed, but the Fatal error shouldn't (IMO) be allowed.
