### ISSUE TITLE
PHP Warning: Undefined variable $extra_headings in tpl_account_history_info_default.php (strict reporting)

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6058]
php 8.3.0RC6, Windows local server, strict_reporting

Buy a product, get a debug:

[20-Nov-2023 16:17:58 UTC] Request URI: /zencart/index.php?main_page=checkout_success, IP address: 127.0.0.1, Language id 1
#0 D:\GitHub\zencart\includes\templates\template_default\templates\tpl_account_history_info_default.php(39): zen_debug_error_handler()
#1 D:\GitHub\zencart\includes\templates\template_default\templates\tpl_checkout_success_default.php(73): require('D:\\GitHub\\zenca...')
#2 D:\GitHub\zencart\includes\templates\responsive_classic\common\tpl_main_page.php(178): require('D:\\GitHub\\zenca...')
#3 D:\GitHub\zencart\index.php(94): require('D:\\GitHub\\zenca...')
--> PHP Warning: Undefined variable $extra_headings in D:\GitHub\zencart\includes\templates\template_default\templates\tpl_account_history_info_default.php on line 39.

Due to the initialisation and subsequent use of $extra_headings being in different clauses:
https://github.com/zencart/zencart/pull/6051/files

**Comment by neekfenwick** [comment]
Looks like my fault.  I'll move the initialisation.
