### ISSUE TITLE
Checkout: PHP Warnings Generated for Downloads

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#6131]
Using the `master` branch as of 20240110 (zc200) with the demo products installed.  Site's `STORE_PRODUCT_TAX_BASIS` is set to "Shipping", using the built-in 3-page checkout with the `ot_loworder_fee` order-total enabled for cart values < $50.00.

Add "Single Download" (index.php?main_page=product_info&products_id=179:57db49fc6391afa689938f5618eb102b) to the cart and go to checkout.  Since the cart's "virtual", the `checkout_shipping` page is bypassed.

A collection of PHP Warning logs are created on entry to the `checkout_payment` page:
```
[10-Jan-2024 18:17:46 America/New_York] Request URI: /zc200w/index.php?main_page=checkout_payment, IP address: 127.0.0.1, Language id 1
#0 C:\xampp\htdocs\zc200w\includes\functions\functions_taxes.php(411): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc200w\includes\modules\order_total\ot_loworderfee.php(94): zen_get_tax_locations()
#2 C:\xampp\htdocs\zc200w\includes\classes\order_total.php(197): ot_loworderfee->process()
#3 C:\xampp\htdocs\zc200w\includes\modules\pages\checkout_payment\header_php.php(101): order_total->pre_confirmation_check()
#4 C:\xampp\htdocs\zc200w\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined array key "entry_zone_id" in C:\xampp\htdocs\zc200w\includes\functions\functions_taxes.php on line 411.

[10-Jan-2024 18:17:46 America/New_York] Request URI: /zc200w/index.php?main_page=checkout_payment, IP address: 127.0.0.1, Language id 1
#0 C:\xampp\htdocs\zc200w\includes\functions\functions_taxes.php(412): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc200w\includes\modules\order_total\ot_loworderfee.php(94): zen_get_tax_locations()
#2 C:\xampp\htdocs\zc200w\includes\classes\order_total.php(197): ot_loworderfee->process()
#3 C:\xampp\htdocs\zc200w\includes\modules\pages\checkout_payment\header_php.php(101): order_total->pre_confirmation_check()
#4 C:\xampp\htdocs\zc200w\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined array key "entry_country_id" in C:\xampp\htdocs\zc200w\includes\functions\functions_taxes.php on line 412.

[10-Jan-2024 18:17:48 America/New_York] Request URI: /zc200w/index.php?main_page=checkout_payment, IP address: 127.0.0.1, Language id 1
#0 C:\xampp\htdocs\zc200w\includes\functions\functions_taxes.php(411): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc200w\includes\modules\order_total\ot_loworderfee.php(94): zen_get_tax_locations()
#2 C:\xampp\htdocs\zc200w\includes\classes\order_total.php(72): ot_loworderfee->process()
#3 C:\xampp\htdocs\zc200w\includes\templates\bootstrap\templates\tpl_checkout_payment_default.php(76): order_total->process()
#4 C:\xampp\htdocs\zc200w\includes\templates\bootstrap\common\tpl_main_page.php(216): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\zc200w\index.php(94): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined array key "entry_zone_id" in C:\xampp\htdocs\zc200w\includes\functions\functions_taxes.php on line 411.

[10-Jan-2024 18:17:48 America/New_York] Request URI: /zc200w/index.php?main_page=checkout_payment, IP address: 127.0.0.1, Language id 1
#0 C:\xampp\htdocs\zc200w\includes\functions\functions_taxes.php(412): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc200w\includes\modules\order_total\ot_loworderfee.php(94): zen_get_tax_locations()
#2 C:\xampp\htdocs\zc200w\includes\classes\order_total.php(72): ot_loworderfee->process()
#3 C:\xampp\htdocs\zc200w\includes\templates\bootstrap\templates\tpl_checkout_payment_default.php(76): order_total->process()
#4 C:\xampp\htdocs\zc200w\includes\templates\bootstrap\common\tpl_main_page.php(216): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\zc200w\index.php(94): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined array key "entry_country_id" in C:\xampp\htdocs\zc200w\includes\functions\functions_taxes.php on line 412.
```

That's because `$_SESSION['sendto']` is `(bool)false`, so the processing in the functions_taxes.php module is met with an empty selection.
https://github.com/zencart/zencart/blob/d3215f505f6bf759aa1f6ad4389bd66d939513d3/includes/functions/functions_taxes.php#L375-L412

**Comment by drbyte** [comment]
The other day you pointed out that `switch(bool)` can produce unexpected results.

Are you proposing that simply changing this to avoid being a `boolean` at this point would be enough?
(Lots of ways to do that: do a `if (bool)` check earlier, or switch to `if/else`, or `match()` or whatever.)

Or did you have something else in mind?

**Comment by lat9** [comment]
That's not a `switch (bool)`, since the `STORE_PRODUCT_TAX_BASIS` is a database configuration setting.  So far, I've only seen this issue when `ot_loworder_fee` is enabled and 'activated', but I'm thinking that changing those settings on lines 411/412 to use the null-coalesce (`??`) operator on the assignments and setting to `'0'` if the associated query resulted in an empty set.

**Comment by drbyte** [comment]
Oh duh. Sorry, I was conflating two very different topics in my earlier post. 🤦‍♂️ 

I agree `?? 0` is probably a good strategy.
