### ISSUE TITLE
Undefined Constant in admin/customers.php

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#6135]
2.0.0 test site
PHP 8.0
bootstrap
OPC

With the release of paypair's beta, we started testing with 2.0.0, the old, and the new PayPal.

We started getting the following error:

`[12-Jan-2024 17:06:58 UTC] PHP Fatal error: Uncaught Error: Undefined constant "error" in /ghul_jet/customers.php:575Stack trace:#0 /ghul_jet/index.php(11): require()#1 {main}thrown in /ghul_jet/customers.php on line 575

[12-Jan-2024 17:06:58 UTC] Request URI: /ghul_jet/index.php?cmd=customers&search=tumania1%40gmail.com&origin=index&page=1&cID=11330&action=edit, IP address: 86.172.98.222--> PHP Fatal error: Uncaught Error: Undefined constant "error" in /ghul_jet/customers.php:575Stack trace:#0 /ghul_jet/index.php(11): require()#1 {main}thrown in /ghul_jet/customers.php on line 575.

[12-Jan-2024 17:06:58 UTC] Request URI: /ghul_jet/index.php?cmd=customers&search=tumania1%40gmail.com&origin=index&page=1&cID=11330&action=edit, IP address: 86.172.98.222--> PHP Fatal error: Uncaught Error: Undefined constant "error" in /ghul_jet/customers.php:575Stack trace:#0 /ghul_jet/index.php(11): require()#1 {main}thrown in /ghul_jet/customers.php on line 575.'

**Comment by scottcwilson** [comment]
Missing dollar sign.  S/b `$error`.

**Comment by dbltoe** [comment]
Yep, that did it.

**Comment by drbyte** [comment]
Fixed by #6136
