### ISSUE TITLE
wrong product type in url causes warning log to be created.

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#6153]
**Describe the bug**
If a url is input for a product that type 1 product_info with the wrong main page which requires additional information like product_music a warning log file is created to say that the additional information is required.
So no my site if you enter the URL 
`https://innerlightcrystals.co.uk/sales/index.php?main_page=product_music_info&products_id=2132`
the product is displayed correctly and a warning log file is created. 
Product_id 2132 is a general product and should be displayed with the url
`https://innerlightcrystals.co.uk/sales/index.php?main_page=product_info&products_id=2132`
I cannot find anything on my site that is creating the incorrect link and was wondering if zen cart should check the product info is being displayed on the correct page for the product type.

**Version**
Zen Cart version: 1.5.8a
PHP version: 8.2
MySQL version: 10.6.16-MariaDB-cll-lve
Plugins that may be related: none
What older/newer versions were also tested? none

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. find a product of type general
2. create a url for that product with a main page of product_music_info
3. warning log file created.

**Expected behavior**
?not sure that there is one

**Debug/Error Logs**
```
[24-Jan-2024 20:22:33 UTC] Request URI: /sales/index.php?main_page=product_music_info&products_id=2132&XDEBUG_SESSION_START=netbeans-xdebug, IP address: 127.0.0.1, Language id 1

#0 /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars_product_type.php(31): zen_debug_error_handler()

#1 /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars.php(108): include_once('...')

#2 /home/lotus/public_html/innerlightcrystals/sales/includes/templates/bootstrap/common/tpl_main_page.php(216): require('...')

#3 /home/lotus/public_html/innerlightcrystals/sales/index.php(94): require('...')

--> PHP Warning: Undefined array key "artists_id" in /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars_product_type.php on line 31.



[24-Jan-2024 20:22:33 UTC] Request URI: /sales/index.php?main_page=product_music_info&products_id=2132&XDEBUG_SESSION_START=netbeans-xdebug, IP address: 127.0.0.1, Language id 1

#0 /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars_product_type.php(36): zen_debug_error_handler()

#1 /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars.php(108): include_once('...')

#2 /home/lotus/public_html/innerlightcrystals/sales/includes/templates/bootstrap/common/tpl_main_page.php(216): require('...')

#3 /home/lotus/public_html/innerlightcrystals/sales/index.php(94): require('...')

--> PHP Warning: Undefined array key "artists_id" in /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars_product_type.php on line 36.



[24-Jan-2024 20:22:33 UTC] Request URI: /sales/index.php?main_page=product_music_info&products_id=2132&XDEBUG_SESSION_START=netbeans-xdebug, IP address: 127.0.0.1, Language id 1

#0 /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars_product_type.php(42): zen_debug_error_handler()

#1 /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars.php(108): include_once('...')

#2 /home/lotus/public_html/innerlightcrystals/sales/includes/templates/bootstrap/common/tpl_main_page.php(216): require('...')

#3 /home/lotus/public_html/innerlightcrystals/sales/index.php(94): require('...')

--> PHP Warning: Undefined array key "record_company_id" in /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars_product_type.php on line 42.



[24-Jan-2024 20:22:33 UTC] Request URI: /sales/index.php?main_page=product_music_info&products_id=2132&XDEBUG_SESSION_START=netbeans-xdebug, IP address: 127.0.0.1, Language id 1

#0 /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars_product_type.php(47): zen_debug_error_handler()

#1 /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars.php(108): include_once('...')

#2 /home/lotus/public_html/innerlightcrystals/sales/includes/templates/bootstrap/common/tpl_main_page.php(216): require('...')

#3 /home/lotus/public_html/innerlightcrystals/sales/index.php(94): require('...')

--> PHP Warning: Undefined array key "record_company_id" in /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars_product_type.php on line 47.



[24-Jan-2024 20:22:33 UTC] Request URI: /sales/index.php?main_page=product_music_info&products_id=2132&XDEBUG_SESSION_START=netbeans-xdebug, IP address: 127.0.0.1, Language id 1

#0 /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars_product_type.php(54): zen_debug_error_handler()

#1 /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars.php(108): include_once('...')

#2 /home/lotus/public_html/innerlightcrystals/sales/includes/templates/bootstrap/common/tpl_main_page.php(216): require('...')

#3 /home/lotus/public_html/innerlightcrystals/sales/index.php(94): require('...')

--> PHP Warning: Undefined array key "music_genre_id" in /home/lotus/public_html/innerlightcrystals/sales/includes/modules/pages/product_music_info/main_template_vars_product_type.php on line 54.
```

 
**Devices (please complete the following information):**
 - Operating System: windows 11
 - Browser [e.g. chrome, firefox] and version number firefox 121.0.1

**Additional context**
I don't know if this is something that should be fixed in zen cart. 
If not, I was thinking of adding observers to check at `NOTIFY_HEADER_START_PRODUCT_MUSIC_INFO` etc. to check the main_page matches the product_type of the product_id and redirect if necessary to the correct main_page type.
Any other suggestions welcome?

**Comment by drbyte** [comment]
It does make sense to double-check that the product_type id pram is valid for the product_id specified.
We do some checking for that when coming from a product-listing where no product_type is provided. But probably should do it in reverse too. I recall there being something in place akin to that, but haven't yet looked at why it's not switching over.

Might be some value it allowing it to display using a product type which is a "parent" to the product's assigned type, if a parent exists. But that might be overkill.

**Comment by brittainmark** [comment]
For me, I created the observer below. Not sure if that is the best way forward, or if there is a better place to put the code?

```
<?php
/* 
 * Observers for mjfb code
 */
class zcObserverMjfbObservers extends base {

    public function __construct() {
        $this->attach(
            $this,
            [
                'NOTIFY_HEADER_START_DOCUMENT_GENERAL_INFO',
                'NOTIFY_HEADER_START_DOCUMENT_PRODUCT_INFO',
                'NOTIFY_HEADER_START_PRODUCT_FREE_SHIPPING_INFO',
                'NOTIFY_HEADER_START_PRODUCT_INFO',
                'NOTIFY_HEADER_START_PRODUCT_MUSIC_INFO',
            ]
        );
    }
    
    protected function updateNotifyHeaderStartDocumentGeneralInfo(&$class, $eventID) {
        //redirect if wrong type handeler
        $this->redirectIncorrectTypeHandler();
    }
    
    protected function updateNotifyHeaderStartDocumentProductInfo(&$class, $eventID) {
        //redirect if wrong type handeler
        $this->redirectIncorrectTypeHandler();
    }
    
    protected function updateNotifyHeaderStartProductInfo(&$class, $eventID) {
        //redirect if wrong type handeler
        $this->redirectIncorrectTypeHandler();
    }
        
    protected function updateNotifyHeaderStartProductMusicInfo(&$class, $eventID) {
        //redirect if wrong type handeler
        $this->redirectIncorrectTypeHandler();
    }
        
    protected function updateNotifyHeaderStartProductFreeShippingInfo(&$class, $eventID) {
        //redirect if wrong type handeler
        $this->redirectIncorrectTypeHandler();
    }
    
    protected function redirectIncorrectTypeHandler(){
        $product_id = $_GET['products_id'] ?? 0;
        $page = $_GET['main_page'];
        if ($product_id === 0) {
            // no product specfied
            $_GET['main_page'] = '';
            //redirect to home page or category if present
            $parameters = $this->getParameters();
            zen_redirect(zen_href_link(FILENAME_DEFAULT, $parameters));
        }  
        $type_handler = zen_get_info_page($product_id);
        if ($type_handler !== $page) {
            // incorrect type handeler redirect to correct type handler
            unset($_GET['main_page']);
            $parameters = $this->getParameters();
            zen_redirect(zen_href_link($type_handler, $parameters));
        }
    }
    
    protected function getParameters() : string {
        $parameters = '';
        foreach ($_GET as $key => $value) {
            if (empty($value) === false) {
                $parameters = '&' . $key . '=' . $value;
            }
        }
        $parameters = substr($parameters, 1);
        return $parameters;
    }
}

```
I was thinking of adding a 301 to the second redirect, as I believe that there may be an incorrect link somewhere (not zen cart) that is causing my problem.

**Comment by drbyte** [comment]
Your logic makes sense to me.

A couple optimizations you could make:
1. Instead of 5 separate `updateNotifierHookName()` functions, you could just use one generic method called `update()`, which will fire on all the attached notifier points if there's no name-specific function declared.

2. Instead of using `getParameters()` as a separate function and calling it after `unset(GET['main_page'])`, you could just use `zen_get_all_get_parameters(['main_page'])`. And, since the default params it strips already includes `main_page`, you can just skip passing that as well.
eg: `zen_redirect(zen_href_link($type_handler, zen_get_all_get_params()))`

I realize you're using an observer so you can trap some other concerns you're investigating, but as far as core code goes, it may be straightforward enough for us to add this to the `header_php.php` file for each product-type:

```diff
$product_info = zen_get_product_details($products_id_current = (!empty($_GET['products_id']) ? (int)$_GET['products_id'] : 0));
+if ($current_page !== $product_info->fields['type_handler'] . '_info') {
+    zen_redirect(zen_href_link($product_info->fields['type_handler'] . '_info', zen_get_all_get_params()));
+}

zen_product_set_header_response($products_id_current, $product_info);
```

**Comment by scottcwilson** [comment]
Closed by PR above.
