### ISSUE TITLE
PayPal logs from 1.5.8 / PHP 8+

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6162]
```
[25-Jan-2024 19:23:20 UTC] Request URI: /ipn_main_handler.php, IP address: .
#0 /home/client/public_html/store/includes/modules/payment/paypal/paypal_functions.php(48): zen_debug_error_handler()
#1 /home/client/public_html/store/includes/init_includes/init_paypal_ipn_sessions.php(34): ipn_get_stored_session()
#2 /home/client/public_html/store/includes/autoload_func.php(40): require_once('/home/client/p...')
#3 /home/client/public_html/store/includes/application_top.php(237): require('/home/client/p...')
#4 /home/client/public_html/store/ipn_main_handler.php(122): require('/home/client/p...')
--> PHP Warning: Undefined array key 1 in /home/client/public_html/store/includes/modules/payment/paypal/paypal_functions.php on line 48.
```

and also (same root cause)

```
[25-Jan-2024 19:23:20 UTC] Request URI: /ipn_main_handler.php, IP address: .
#0 [internal function]: zen_debug_error_handler()
#1 /home/client/public_html/store/includes/classes/db/mysql/query_factory.php(561): preg_match()
#2 /home/client/public_html/store/includes/classes/db/mysql/query_factory.php(513): queryFactory->getBindVarValue()
#3 /home/client/public_html/store/includes/modules/payment/paypal/paypal_functions.php(48): queryFactory->bindVars()
#4 /home/client/public_html/store/includes/init_includes/init_paypal_ipn_sessions.php(34): ipn_get_stored_session()
#5 /home/client/public_html/store/includes/autoload_func.php(40): require_once('/home/client/p...')
#6 /home/client/public_html/store/includes/application_top.php(237): require('/home/client/p...')
#7 /home/client/public_html/store/ipn_main_handler.php(122): require('/home/client/p...')
--> PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/client/public_html/store/includes/classes/db/mysql/query_factory.php on line 561.
```

Don't see an update in 2.0.0 for this.

**Comment by scottcwilson** [comment]
This would definitely do it.  I was just wondering if others were seeing it too.

**Comment by scottcwilson** [comment]
Thanks for fixing!  Closed by direct commit noted above.
