### ISSUE TITLE
Blank page when trying to delete, move or copy product

### ISSUE THREAD

**Issue by piloujp** [zencart/zencart#6522]
Got blank pages when trying to delete, move or copy a product in admin.

Latest GitHub version with PHP 8.3 used.

Log has this error message:
```
[06-Jun-2024 18:24:19 Asia/Tokyo] PHP Fatal error:  Uncaught TypeError: zen_get_admin_module_from_directory(): Argument #1 ($product_type) must be of type int, string given, called in ...\testcart\admin\category_product_listing.php on line 223 and defined in ...\testcart\includes\functions\functions_files.php:205
Stack trace:
#0 ...\testcart\admin\category_product_listing.php(223): zen_get_admin_module_from_directory()
#1 ...\testcart\admin\index.php(16): require('...')
#2 {main}
  thrown in ...\testcart\includes\functions\functions_files.php on line 205

```
It seems the problem is coming from function 'zen_get_admin_module_from_directory' in '...\includes\functions\functions_files.php' which expects an integer as product type argument but receives a string. 

When I try to fix it with this:
`function zen_get_admin_module_from_directory(int|string $product_type, string $filename_to_check, bool $dir_only = false): string`
I got another error message:

```
[06-Jun-2024 18:43:31 Asia/Tokyo] PHP Fatal error:  Uncaught TypeError: mysqli_real_escape_string(): Argument #2 ($string) must be of type string, array given in ...\testcart\includes\classes\db\mysql\query_factory.php:201
Stack trace:
#0 ...\testcart\includes\classes\db\mysql\query_factory.php(201): mysqli_real_escape_string()
#1 ...\testcart\includes\functions\database.php(28): queryFactory->prepare_input()
#2 ...\testcart\admin\includes\modules\copy_product_confirm.php(81): zen_db_input()
#3 ...\testcart\admin\category_product_listing.php(229): require('...')
#4 ...\testcart\admin\index.php(16): require('...')
#5 {main}
  thrown in ...\testcart\includes\classes\db\mysql\query_factory.php on line 201
```
This one might not be directly related.

**Comment by scottcwilson** [comment]
Dup of #6504 ?

**Comment by piloujp** [comment]
Oh yes... I have seen it yesterday but forgot... Second error message is related to it, no doubt, but first error caused by wrong argument type is not treated in proposed PR #6521.

**Comment by drbyte** [comment]
> Oh yes... I have seen it yesterday but forgot... Second error message is related to it, no doubt, but first error caused by wrong argument type is not treated in proposed PR #6521.

Should be fixed by #6520
