### ISSUE TITLE
Clicking green box to disabled featured category creates a white screen

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6686]
Choose a featured category without start/end dates.

```
[25-Aug-2024 09:34:52 UTC] Request URI: /gh_demo_200/admin/index.php?cmd=featured_categories&action=setflag, IP address: ::1, Language id 1
#0 [internal function]: zen_debug_error_handler()
#1 /Users/scott/Sites/gh_demo_200/includes/classes/db/mysql/query_factory.php(720): trigger_error()
#2 /Users/scott/Sites/gh_demo_200/includes/classes/db/mysql/query_factory.php(665): queryFactory->show_error()
#3 /Users/scott/Sites/gh_demo_200/includes/classes/db/mysql/query_factory.php(299): queryFactory->set_error()
#4 /Users/scott/Sites/gh_demo_200/includes/functions/featured.php(110): queryFactory->Execute()
#5 /Users/scott/Sites/gh_demo_200/admin/featured_categories.php(27): zen_set_featured_category_status()
#6 /Users/scott/sites/gh_demo_200/admin/index.php(16): require('/Users/scott/Si...')
--> PHP Fatal error: MySQL error 1054: Unknown column 'featured_id' in 'where clause' :: UPDATE featured_categories
          SET status = 0,
              date_status_change = now()
          WHERE featured_id = 9 ==> (as called by) /Users/scott/Sites/gh_demo_200/includes/functions/featured.php on line 110 <== in /Users/scott/Sites/gh_demo_200/includes/classes/db/mysql/query_factory.php on line 720.
```

**Comment by scottcwilson** [comment]
Note that the "Delete featured category" button in the infobox *does* work as expected.
