### ISSUE TITLE
Small POSM issue

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6862]
```
[20-Nov-2024 19:53:24 UTC] Request URI: /admin/index.php?cmd=products_options_stock&pID=3414, IP address: ***, Language id 1
#0 /home/client/public_html/zc_plugins/POSM/v6.0.0/admin/products_options_stock.php(1262): zen_debug_error_handler()
#1 /home/client/public_html/admin/index.php(28): require('/home/client/...')
--> PHP Warning: Undefined array key 86 in /home/client/public_html/zc_plugins/POSM/v6.0.0/admin/products_options_stock.php on line 1262.
```

Possible fix: change 
```
            $option_value_name = zen_values_name($info_array['options'][$option_id]);
```
to
```
            $option_value_name = zen_values_name($info_array['options'][$option_id] ?? -1);
```

**Comment by lat9** [comment]
So, what's the story with product id 3414's option id 86?  How are the product's options defined?

**Comment by scottcwilson** [comment]
I suspect it was an old option which was improperly deleted.

**Comment by scottcwilson** [comment]
Please give me the relevant queries you'd like to see.  I looked at the code and can't easily see how to work backwards.

**Comment by lat9** [comment]
Two queries:
```
SELECT * FROM products_options_stock_attributes WHERE products_id = 3414;

SELECT * FROM products_attributes WHERE products_id = 3414;
```

**Comment by scottcwilson** [comment]
```
mysql> SELECT * FROM products_options_stock_attributes WHERE products_id = 3414;
+------------------+--------+-------------+------------+-------------------+
| pos_attribute_id | pos_id | products_id | options_id | options_values_id |
+------------------+--------+-------------+------------+-------------------+
|            56134 |  10997 |        3414 |         83 |               400 |
|            56133 |  10997 |        3414 |         82 |               918 |
|            56132 |  10997 |        3414 |         86 |               418 |
|            56155 |  11004 |        3414 |         83 |               406 |
|            56154 |  11004 |        3414 |         82 |               410 |
|            56153 |  11004 |        3414 |         86 |               419 |
|            56143 |  11000 |        3414 |         83 |               400 |
|            56142 |  11000 |        3414 |         82 |               410 |
|            56141 |  11000 |        3414 |         86 |               419 |
|            56140 |  10999 |        3414 |         83 |               400 |
|            56139 |  10999 |        3414 |         82 |               410 |
|            56138 |  10999 |        3414 |         86 |               418 |
+------------------+--------+-------------+------------+-------------------+
12 rows in set (0.00 sec)
```

```
mysql> SELECT * FROM products_attributes WHERE products_id = 3414;
+------------------------+-------------+------------+-------------------+----------------------+------------------------+--------------+-----------------------------+---------------------------+----------------------------+-----------------------------------+-------------------------+--------------------+-----------------------+------------------+--------------------------------+--------------------------+-------------------------+--------------------------------+---------------------------------+----------------------------------------+-----------------------+-------------------------------+------------------------+-----------------------------+--------------------------+-------------------------------+---------------------+
| products_attributes_id | products_id | options_id | options_values_id | options_values_price | options_values_price_w | price_prefix | products_options_sort_order | product_attribute_is_free | products_attributes_weight | products_attributes_weight_prefix | attributes_display_only | attributes_default | attributes_discounted | attributes_image | attributes_price_base_included | attributes_price_onetime | attributes_price_factor | attributes_price_factor_offset | attributes_price_factor_onetime | attributes_price_factor_onetime_offset | attributes_qty_prices | attributes_qty_prices_onetime | attributes_price_words | attributes_price_words_free | attributes_price_letters | attributes_price_letters_free | attributes_required |
+------------------------+-------------+------------+-------------------+----------------------+------------------------+--------------+-----------------------------+---------------------------+----------------------------+-----------------------------------+-------------------------+--------------------+-----------------------+------------------+--------------------------------+--------------------------+-------------------------+--------------------------------+---------------------------------+----------------------------------------+-----------------------+-------------------------------+------------------------+-----------------------------+--------------------------+-------------------------------+---------------------+
|                   2598 |        3414 |         82 |               410 |               0.0000 | 0                      | +            |                          13 |                         1 |                          0 | +                                 |                       0 |                  0 |                     1 |                  |                              1 |                   0.0000 |                  0.0000 |                         0.0000 |                          0.0000 |                                 0.0000 |                       |                               |                 0.0000 |                           0 |                   0.0000 |                             0 |                   0 |
|                   2597 |        3414 |         82 |               918 |               0.0000 | 0                      | +            |                          11 |                         1 |                          0 | +                                 |                       0 |                  0 |                     1 |                  |                              1 |                   0.0000 |                  0.0000 |                         0.0000 |                          0.0000 |                                 0.0000 |                       |                               |                 0.0000 |                           0 |                   0.0000 |                             0 |                   0 |
|                   2600 |        3414 |         83 |               400 |               0.0000 | 0                      | +            |                           3 |                         1 |                          0 | +                                 |                       0 |                  0 |                     1 |                  |                              1 |                   0.0000 |                  0.0000 |                         0.0000 |                          0.0000 |                                 0.0000 |                       |                               |                 0.0000 |                           0 |                   0.0000 |                             0 |                   0 |
|                   2599 |        3414 |         83 |               406 |               0.0000 | 0                      | +            |                           7 |                         1 |                          0 | +                                 |                       0 |                  0 |                     1 |                  |                              1 |                   0.0000 |                  0.0000 |                         0.0000 |                          0.0000 |                                 0.0000 |                       |                               |                 0.0000 |                           0 |                   0.0000 |                             0 |                   0 |
|                   2595 |        3414 |         86 |               418 |               0.0000 | 0                      | +            |                           5 |                         1 |                          0 | +                                 |                       0 |                  0 |                     1 |                  |                              1 |                   0.0000 |                  0.0000 |                         0.0000 |                          0.0000 |                                 0.0000 |                       |                               |                 0.0000 |                           0 |                   0.0000 |                             0 |                   0 |
|                   2596 |        3414 |         86 |               419 |               0.0000 | 0                      | +            |                           7 |                         1 |                          0 | +                                 |                       0 |                  0 |                     1 |                  |                              1 |                   0.0000 |                  0.0000 |                         0.0000 |                          0.0000 |                                 0.0000 |                       |                               |                 0.0000 |                           0 |                   0.0000 |                             0 |                   0 |
+------------------------+-------------+------------+-------------------+----------------------+------------------------+--------------+-----------------------------+---------------------------+----------------------------+-----------------------------------+-------------------------+--------------------+-----------------------+------------------+--------------------------------+--------------------------+-------------------------+--------------------------------+---------------------------------+----------------------------------------+-----------------------+-------------------------------+------------------------+-----------------------------+--------------------------+-------------------------------+---------------------+
6 rows in set (0.01 sec)
```

**Comment by lat9** [comment]
OK, two more
```
SELECT * FROM products_options WHERE products_options_id = 86;

SELECT * FROM products_options_values WHERE products_options_values_id IN [418, 419];
```

**Comment by scottcwilson** [comment]
```
mysql> SELECT * FROM products_options WHERE products_options_id = 86;
+---------------------+-------------+-----------------------+-----------------------------+-----------------------+-------------------------+--------------------------+-----------------------------------+-----------------------+---------------------------------+-------------------------------+-----------------------+
| products_options_id | language_id | products_options_name | products_options_sort_order | products_options_type | products_options_length | products_options_comment | products_options_comment_position | products_options_size | products_options_images_per_row | products_options_images_style | products_options_rows |
+---------------------+-------------+-----------------------+-----------------------------+-----------------------+-------------------------+--------------------------+-----------------------------------+-----------------------+---------------------------------+-------------------------------+-----------------------+
|                  86 |           1 | # LUGS                |                          15 |                     0 |                      32 |                          |                                 0 |                    32 |                               5 |                             0 |                     1 |
+---------------------+-------------+-----------------------+-----------------------------+-----------------------+-------------------------+--------------------------+-----------------------------------+-----------------------+---------------------------------+-------------------------------+-----------------------+
1 row in set (0.02 sec)
```

```
mysql> SELECT * FROM products_options_values WHERE products_options_values_id IN (418, 419);
+----------------------------+-------------+------------------------------+------------------------------------+
| products_options_values_id | language_id | products_options_values_name | products_options_values_sort_order |
+----------------------------+-------------+------------------------------+------------------------------------+
|                        418 |           1 | 5-LUG                        |                                  5 |
|                        419 |           1 | 6-LUG                        |                                  7 |
+----------------------------+-------------+------------------------------+------------------------------------+
2 rows in set (0.08 sec)
```

**Comment by lat9** [comment]
... and _finally_ (hopefully):
```
SELECT configuration_key, configuration_value FROM configuration WHERE configuration_key IN ('POSM_OPTIONAL_OPTION_TYPES_LIST', 'POSM_OPTIONAL_OPTION_NAMES_LIST', 'POSM_OPTIONS_TYPES_TO_MANAGE');
```

**Comment by scottcwilson** [comment]
```
mysql> SELECT configuration_key, configuration_value FROM configuration WHERE configuration_key IN ('POSM_OPTIONAL_OPTION_TYPES_LIST', 'POSM_OPTIONAL_OPTION_NAMES_LIST', 'POSM_OPTIONS_TYPES_TO_MANAGE');

+---------------------------------+---------------------+
| configuration_key               | configuration_value |
+---------------------------------+---------------------+
| POSM_OPTIONAL_OPTION_NAMES_LIST |                     |
| POSM_OPTIONAL_OPTION_TYPES_LIST |                     |
| POSM_OPTIONS_TYPES_TO_MANAGE    | 0,2                 |
+---------------------------------+---------------------+
3 rows in set (1.96 sec)
```

**Comment by lat9** [comment]
Another, because this is just not making sense to me:
```
SELECT DISTINCT pa.options_id, po.products_options_name as options_name, LPAD(po.products_options_sort_order, 11, '0') as sort_order
           FROM products_options po
                INNER JOIN products_attributes pa
                    ON pa.options_id = po.products_options_id
                   AND pa.products_id = 3414
          WHERE po.products_options_type  IN (0, 2)
            AND po.language_id = 1
       ORDER BY sort_order ASC, po.products_options_name ASC
```

**Comment by scottcwilson** [comment]
```
mysql> SELECT DISTINCT pa.options_id, po.products_options_name as options_name, LPAD(po.products_options_sort_order, 11, '0') as sort_order
    ->            FROM products_options po
    ->                 INNER JOIN products_attributes pa
    ->                     ON pa.options_id = po.products_options_id
    ->                    AND pa.products_id = 3414
    ->           WHERE po.products_options_type  IN (0, 2)
    ->             AND po.language_id = 1
    ->        ORDER BY sort_order ASC, po.products_options_name ASC
    ->
    -> ;
+------------+--------------+-------------+
| options_id | options_name | sort_order  |
+------------+--------------+-------------+
|         86 | # LUGS       | 00000000015 |
|         82 | TIRE SIZE    | 00000000020 |
|         83 | RADIAL / PLY | 00000000025 |
+------------+--------------+-------------+
3 rows in set (0.14 sec)
```
