### ISSUE TITLE
encapsulated plugin: not loading "pages/product_info/header_php_myplugin.php" from plugins

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6874]
installer, admin side is working.

catalog is failing to look for the header file in the plugins structure.

>  Request URI: /zencart-210/index.php?main_page=product_info&cPath=1_8&products_id=25, IP address: 127.0.0.1, Language id 1
> #0 ...\zencart-210\index.php(35): zen_debug_error_handler()
> #1 ...\zencart-210\index.php(35): require()
> --> PHP Warning: require(includes/modules/pages/product_info/header_php_gpsr.php): Failed to open stream: No such file or directory in ...\zencart-210\index.php on line 35.

Header code is to set a flag, so maybe could go elsewhere if not possible here.

**Comment by lat9** [comment]
Noting that a similar issue arises if a zc_plugin includes a page-specific `jscript_*.php` or `jscript_*.js` file.

**Comment by lat9** [comment]
For right now, those page-specific 'extra' files aren't supported (obviously) in zc_plugins.

Part of the issue, IMO, is the use of the `$template->get_template_part` method to retrieve those matching page-specific files ... which have _no_ template-related part.  Changes to enable zc_plugins to provide these files will have repercussions on templates' CSS/JS file loaders.

**Comment by torvista** [comment]
I copied POSM and used observers to check the page and 
- do the necessary code for a specific page
- insertion of default AND template css
- footer loading of default OR template jscript

As this is all doable without any futher core mods, I would leave it as is, just needs documenting.

A simple demo plugin would be useful that covers all these bases for catalog.
My upcoming GPSR plugin could be stripped back to serve as an example, once reviewed.
