### ISSUE TITLE
admin, search results: current_category_id=0 on attribute action button

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6892]
![2024-12-17 16_42_23-](https://github.com/user-attachments/assets/ebed4d23-5723-466d-bfd5-4a41da76cb3b)
eg. search for dvd.
In the results, the products that do not have any attributes, have a current_category_id=0 so when passing to attributes_controller, page load fails with a debug.

**Comment by lat9** [comment]
... and the debug-log's contents?

**Comment by torvista** [comment]
[Request URI: /zencart/admin/index.php?cmd=attributes_controller&products_filter=20&current_category_id=0
#0 D:\GitHub\zencart\admin\attributes_controller.php(1962): zen_debug_error_handler()
#1 D:\GitHub\zencart\admin\index.php(16): require('D:\\GitHub\\zenca...')
--> PHP Warning: Undefined variable $attributes_value in D:\GitHub\zencart\admin\attributes_controller.php on line 1962.

**Comment by torvista** [comment]
Hmm, that's on a vanilla site, but it doesn't die.

(I find I get a different error on production...and it bypasses the interim infobox. So, I don't escape completely.)

**Comment by torvista** [comment]
As I had strict mode in functions_categories, it was failing here:
https://github.com/zencart/zencart/blob/8333810225d0e0ec45c6aa51e97cef1bc0302e5b/includes/functions/functions_categories.php#L381

without strict mode, it continues to attributes_controller but oddly without generating the warning that occurs in the vanilla site!
